-- Active: 1710930161670@@127.0.0.1@5432@postgres

-- Fullfill Specific Tables --

-- Units table -- Unit_type could be: Infantry, Bikes - Jetbikes, Artillery, Jumps, Jet Packs, Beasts, Cavalry, Monsters, Vehicles, Flyers
INSERT INTO units (Unit_name, Faction_id, Unit_type, Nb_fig, M, BS, WS, S, T, W, A, I, Ld, OC, Sv, Invul_sv,
                   Keywords, Aptitude_name, Aptitude_desc, U_Pts)
VALUES
    ('CHAPLAIN GRIMALDUS', 1, 'Infantry', 1, '6"', '2+', '2+', 4, 4, 5, 4, 4, '6+', 1, '3+', '4++',
     'INFANTRY, CHARACTER, PRIEST, MASTER OF SANCTITY, CHAPLAIN, GRIMALDUS',
     ARRAY['Litanies of the Devout','Unmatched Zeal'],
     ARRAY['While Chaplain Grimaldus is leading a unit, each time a model in that unit makes a melee attack, you can re-roll the Hit roll.',
        'Friendly Black Templars units within 6" of Chaplain Grimaldus have the Zealot special rule.'],
     150)
;

-- Units Rules tables
INSERT INTO units_rules (unit_id, Rule_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Units Psy tables
INSERT INTO units_psy (unit_id, domains_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Units Rules tables
INSERT INTO units_weapons (unit_id, weapon_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Weapons table -- Weapon type could be: Melee, Assault - Heavy, Ordnance, Pistol, Psychic, Rapid Fire, Salvo, Bombs or Primary
INSERT INTO weapons (group_faction_id, Weapon_name, Weapon_type, Range, A, S, AP, D, W_Pts)
VALUES
    (1, 'Bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (1, 'Heavy bolt pistol', 'Pistol', '18"', '1', '4', '-1', '1', 5),
    (1, 'Special issue bolt pistol', 'Pistol - Precision Shots', '12"', '1', '4', '0', '2', 0),
    (1, 'Absolvor bolt pistol', 'Pistol', '18"', '1', '5', '-1', '2', 5),
    (1, 'Assault boltgun', 'Pistol - Assault - Twin-linked - Sustained Hits 2', '18"', '3', '5', '-1', '2', 10),
    (1, 'Boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Boltrifle', 'Assault - Heavy', '24"', '2', '4', '-1', '1', 5),
    (1, 'Twin boltrifle', 'Assault - Heavy - Twin-linked', '24"', '2', '4', '-1', '1', 10),
    (1, 'Boltstorm', 'Pistol', '12"', '3', '4', '-1', '1', 5),
    (1, 'Instigator bolt carbine', 'Assault - Precision Shots', '30"', '1', '4', '-2', '2', 10),
    (1, 'Occulus bolt carbine', 'Assault - Precision Shots - Ignores Cover', '30"', '2', '4', '0', '2', 10),
    (1, 'Marksman bolt carbine', 'Heavy - Lethal Hits', '24"', '2', '4', '0', '2', 5),
    (1, 'Stalker pattern boltgun', 'Heavy - Sniper', '30"', '2', '4', '-1', '1', 5),
    (1, 'Bolt sniper rifle', 'Heavy - Sniper', '36"', '1', '5', '-2', '3', 10),
    (1, 'Ammunition Dragonfire Bolt', 'Ignores Cover', '=', '=', '=', 'Minus 1', '=', 0),
    (1, 'Ammunition Hellfire Round', 'Poisoned (2+)', '=', '=', '-3', 'Minus 1', '=', 0),
    (1, 'Ammunition Kraken Bolt', 'Concussive', '+25%', '=', '=', 'Minus 2', '=', 0),
    (1, 'Ammunition Vengeance Round', 'Gets Hot', '-25%', '=', '=', 'Minus 3', '=', 0),
    (1, 'Twin boltgun', 'Rapid Fire 1 - Twin-linked', '24"', '2', '4', '0', '1', 5),
    (1, 'Hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 15),
    (1, 'Twin hurricane boltgun', 'Rapid Fire 6 - Twin-linked', '24"', '6', '4', '0', '1', 20),
    (1, 'Heavy bolter', 'Heavy - Sustained Hit 1', '36"', '3', '5', '-1', '2', 10),
    (1, 'Twin heavy bolter', 'Heavy - Twin-linked - Sustained Hit 1', '36"', '3', '5', '-1', '2', 15),
    (1, 'Storm bolter', 'Assault - Rapid Fire 2', '24"', '2', '4', '0', '1', 0),
    (1, 'Condemnor strake (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Condemnor strake (Crossbow)', 'Assault - Rapid Fire 1 - Precision Strikes - Devastating Wounds - Psy-Shock', '24"', '1', '5', '0', '1', 5),
    (1, 'Infernus heavy bolter (Heavy bolter)', 'Assault - Heavy - Sustained Hit 1', '36"', '3', '5', '-1', '2', 10),
    (1, 'Infernus heavy bolter (Heavy Flamer)', 'Assault - Heavy - Ignores Cover', 'Template', '1', '5', '-1', '1', 10),
    (1, 'Infernus heavy bolter (Hellfire shell)', 'Heavy - Blast - Poisoned (2+)', '24"', '1', '1', '0', 'D3', 10),
    (1, 'Hand flamer', 'Pistol - Ignores Cover', 'Template', '1', '3', '0', '1', 5),
    (1, 'Flamer', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 10),
    (1, 'Combi-flamer (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-flamer (Flamer)', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 10),
    (1, 'Hellfire Extremis (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Hellfire Extremis (Hellfire)', 'Assault - Ignores Cover', 'Template', '1', '4', '-1', '2', 10),
    (1, 'Heavy flamer', 'Assault - Ignores Cover', 'Template', '1', '5', '-1', '1', 10),
    (1, 'Twin heavy flamer', 'Assault - Ignores Cover - Twin-linked', 'Template', '1', '5', '-1', '2', 15),
    (1, 'Pyroclast flame projector (Dispersed)', 'Assault - Ignores Cover', 'Template', '1', '6', '-1', '1', 10),
    (1, 'Pyroclast flame projector (Focused)', 'Assault - Melta', '6"', '1', '7', '-5', 'D6', 10),
    (1, 'Dreadfire heavy flamer (Separated)', 'Assault - Ignores Cover - Devastating Wounds', 'Template', '2', '5', '-1', '1', 10),
    (1, 'Dreadfire heavy flamer (Combined)', 'Assault - Ignores Cover - Devastating Wounds - Melta', 'Template', '1', '9', '-4', 'D3+3', 10),
    (1, 'Incendium cannon', 'Assault - Heavy - Ignores Cover', 'Template', '1', '4', '0', 'D3', 5),
    (1, 'Incendine combustor', 'Assault - Ignores Cover', 'Template', '1', '6', '-1', '1', 10),
    (1, 'Neo-volkite pistol', 'Pistol - Devastating Wounds', '12"', '1', '5', '0', '2', 5),
    (1, 'Meltagun', 'Assault - Melta', '12"', '1', '9', '-4', 'D6', 10),
    (1, 'Meltarifle', 'Heavy', '18"', '1', '9', '-4', 'D6', 15),
    (1, 'Combi-melta (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-melta (Meltagun)', 'Assault - Melta', '12"', '1', '9', '-4', 'D6', 10),
    (1, 'Multi-melta', 'Heavy - Melta', '18"', '2', '9', '-4', 'D6', 20),
    (1, 'Twin multi-melta', 'Heavy - Twin-linked - Melta', '18"', '2', '9', '-4', 'D6', 25),
    (1, 'Thermal spear', 'Assault - Melta', '24"', '2', '12', '-4', 'D6', 30),
    (1, 'Thermal cannon', 'Heavy - Melta - Large Blast', '24"', '2D3', '12', '-4', 'D6', 35),
    (1, 'Grav-pistol', 'Pistol - Concussive - Graviton - Anti-Vehicle', '12"', '1', '4', '-1', '1', 5),
    (1, 'Grav-gun', 'Salvo 2/3 - Concussive - Graviton - Anti-Vehicle', '18"', '2', '5', '-1', '2', 10),
    (1, 'Combi-grav (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-grav (Grav-gun)', 'Salvo 2/3 - Concussive - Graviton - Anti-Vehicle', '18"', '2', '5', '-1', '2', 10),
    (1, 'Grav-cannon', 'Salvo 3/5 - Concussive - Graviton - Anti-Vehicle', '30"', '4', '5', '-1', '2', 15),
    (1, 'Plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (1, 'Plasma pistol (Supercharge)', 'Pistol - Gets Hot', '12"', '1', '8', '-3', '2', 5),
    (1, 'Plasma gun (Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (1, 'Plasma gun (Supercharge)', 'Rapid Fire 1 - Gets Hot', '24"', '1', '8', '-3', '2', 10),
    (1, 'Plasma cutter', 'Assault- Gets Hot - Twin-linked', '12"', '1', '7', '-2', '1', 10),
    (1, 'Plasma incinerator (Standard)', 'Assault - Heavy', '24"', '2', '7', '-2', '1', 5),
    (1, 'Plasma incinerator (Supercharge)', 'Assault - Heavy - Gets Hot', '24"', '2', '8', '-3', '2', 10),
    (1, 'Plasma caliver (Standard)', 'Assault', '24"', '2', '7', '-2', '1', 5),
    (1, 'Plasma caliver (Supercharge)', 'Assault - Gets Hot', '24"', '2', '8', '-3', '2', 5),
    (1, 'Combi-plasma (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-plasma (Plasma gun Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (1, 'Combi-plasma (Plasma gun Supercharge)', 'Rapid Fire 1 - Gets Hot', '24"', '1', '8', '-3', '2', 10),
    (1, 'Plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (1, 'Plasma cannon (Supercharge)', 'Heavy - Gets Hot - Blast', '36"', '1', '8', '-3', '2', 10),
    (1, 'Twin plasma cannon (Standard)', 'Heavy - Twin-linked', '36"', '1', '7', '-2', '1', 10),
    (1, 'Twin plasma cannon (Supercharge)', 'Heavy - Gets Hot - Twin-linked - Blast', '36"', '1', '8', '-3', '2', 15),
    (1, 'Heavy plasma cannon (Standard)', 'Heavy - Blast', '36"', 'D3', '7', '-2', '1', 15),
    (1, 'Heavy plasma cannon (Supercharge)', 'Heavy - Gets Hot - Large Blast', '36"', 'D3', '8', '-3', '2', 15),
    (1, 'Twin heavy plasma cannon (Standard)', 'Heavy - Twin-linked - Blast', '36"', 'D3', '7', '-2', '1', 15),
    (1, 'Twin heavy plasma cannon (Supercharge)', 'Heavy - Gets Hot - Twin-linked - Large Blast', '36"', 'D3', '8', '-3', '2', 20),
    (1, 'Frag cannon (Frag round)', 'Assault - Heavy - Rapid Fire D3 - Blast', '18"', '2', '6', '0', '1', 10),
    (1, 'Frag cannon (Solid shell)', 'Assault - Heavy', '24"', '2', '7', '-3', 'D6', 10),
    (1, 'Ironhail heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '0', '1', 5),
    (1, 'Twin ironhail heavy stubber', 'Rapid Fire 3 - Twin-linked', '36"', '3', '4', '0', '1', 10),
    (1, 'Questoris heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '-1', '1', 5),
    (1, 'Accelerator autocannon', 'Heavy', '48"', '3', '8', '-1', '2', 20),
    (1, 'Armiger autocannon', 'Heavy', '48"', '4', '9', '-1', '3', 25),
    (1, 'Icarus autocannon', 'Heavy - Twin-linked - Anti-Flyer - Interceptor - Sky fire', '48"', '3', '7', '-1', '2', 20),
    (1, 'Rapid fire battle cannon', 'Heavy - Rappid Fire D6+3 - Blast', '72"', '3', '10', '-1', 'D3+3', 50),
    (1, 'Predator autocannon', 'Heavy - Rapid Fire 2', '48"', '4', '9', '-1', '3', 30),
    (1, 'Predator twin lascannon', 'Heavy - Twin-linked', '48"', '1', '14', '-3', 'D6+1', 30),
    (1, 'Lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 20),
    (1, 'Twin lascannon', 'Heavy - Twin-linked', '48"', '1', '12', '-3', 'D6+1', 25),
    (1, 'Las-talon', 'Heavy', '36"', '2', '10', '-3', 'D6+1', 15),
    (1, 'Assault cannon', 'Heavy - Rending - Devastating Wounds', '24"', '6', '6', '0', '1', 15),
    (1, 'Twin assault cannon', 'Heavy - Twin-linked - Rending - Devastating Wounds', '24"', '6', '6', '0', '1', 20),
    (1, 'Onslaught gatling cannon', 'Heavy - Devastating Wounds', '24"', '8', '6', '0', '1', 15),
    (1, 'Avenger gatling cannon', 'Heavy - Rending', '36"', '18', '6', '-2', '2', 35),
    (1, 'Arc pistol', 'Pistol - Anti-Vehicles - Haywire - Devastating Wounds', '12"', '1', '6', '-1', '1', 10),
    (1, 'Arc rifle', 'Rapid fire 1 - Anti-Vehicles - Haywire - Devastating Wounds', '30"', '1', '8', '-1', 'D3', 10),
    (1, 'Phosphor serpenta', 'Pistol - Ignores Cover - Assault - Luminagen', '18"', '1', '5', '-1', '2', 10),
    (1, 'Heavy phosphor blaster', 'Heavy - Ignores Cover - Luminagen', '36"', '3', '6', '-1', '2', 20),
    (1, 'Kastelan phosphor blaster', 'Heavy', '24"', '3', '6', '-1', '1', 15),
    (1, 'Twin kastelan phosphor blaster', 'Heavy - Twin-linked - Ignores Cover - Luminagen', '24"', '3', '6', '-1', '1', 20),
    (1, 'Onager heavy phosphor blaster', 'Heavy - Ignores Cover - Luminagen', '36"', '4', '6', '-1', '2', 25),
    (1, 'Twin onager heavy phosphor blaster', 'Heavy - Twin-linked - Ignores Cover - Luminagen', '36"', '4', '6', '-1', '2', 30),
    (1, 'Macrostubber', 'Pistol - Burst Pistol', '12"', '5', '4', '0', '1', 5),
    (1, 'Cognis heavy stubber', 'Rapid fire 3 - Sustained Hit 1', '36"', '3', '4', '0', '1', 5),
    (1, 'Gamma pistol', 'Pistol - Devastating Wounds - Armourbane', '24"', '1', '6', '-1', 'D3', 10),
    (1, 'Solar atomiser', 'Assault - Blast - Melta', '18"', 'D3', '14', '-4', '3', 25),
    (1, 'Volkite blaster', 'Heavy - Devastating Wounds - Deflagrate', '24"', '3', '5', '0', '2', 5),
    (1, 'Eradication ray (Dissipated)', 'Heavy - Blast', '24"', '1', '6', '-1', 'D3', 10),
    (1, 'Eradication ray (Focused)', 'Heavy', '12"', 'D3', '8', '-2', '2', 10),
    (1, 'Eradication beamer (Dissipated)', 'Heavy - Blast - Sustained Hit D3', '36"', '2', '9', '-2', '1', 15),
    (1, 'Eradication beamer (Focused)', 'Heavy - Blast - Sustained Hit D3', '18"', '3', '9', '-3', 'D6', 15),
    (1, 'Galvanic rifle', 'Assault', '30"', '2', '4', '0', '1', 0),
    (1, 'Radium pistol', 'Pistol - Anti-Infantry', '12"', '1', '3', '0', '1', 0),
    (1, 'Radium carbine', 'Assault - Anti-Infantry', '18"', '3', '3', '0', '1', 0),
    (1, 'Transuranic arquebus', 'Heavy - Precision Shots', '36"', '1', '7', '-2', 'D3', 15),
    (1, 'Neutron laser', 'Heavy - Blast - Armourbane', '48"', '2', '16', '-4', '2', 35),
    (1, 'Missile launcher (Frag)', 'Heavy - Blast', '48"', '1', '4', '0', '1', 10),
    (1, 'Missile launcher (Krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (1, 'Icarus array', 'Heavy - Twin-linked - Anti-Flyer', '48"', '6', '8', '-1', '2', 15),
    (1, 'Typhoon missile launcher (Frag)', 'Heavy - Blast', '48"', '2', '4', '0', '1', 10),
    (1, 'Typhoon missile launcher (Krak)', 'Heavy', '48"', '2', '9', '-2', 'D6', 10),
    (1, 'Stormstrike missile launcher', 'Heavy - One Use Only - Lethal Hits - Concussive', '48"', '1', '8', '-4', 'D6', 20),
    (1, 'Skyhammer missile launcher', 'Heavy', '60"', '3', '7', '-1', 'D3', 20),
    (1, 'Deathwind launcher', 'Heavy - Large Blast', '12"', '1', '12', '0', 'D6+1', 5),
    (1, 'Fragstorm grenade launcher', 'Heavy - Blast', '18"', 'D3', '4', '0', '1', 5),
    (1, 'Ironstorm missile pod', 'Heavy - Large Blast - Barrage - Indirect Fire', '48"', '1', '5', '0', 'D3', 20),
    (1, 'Hellfyre missile rack', 'Heavy', '36"', '2', '10', '-2', '3', 25),
    (1, 'Daedalus missile launcher', 'Heavy - Anti-Flyer', '48"', '1', '10', '-2', 'D6+1', 20),
    (1, 'Blackstar rocket launcher (Corvid warhead)', 'Heavy - Sky Fire', '30"', 'D6', '6', '-2', 'D6', 10),
    (1, 'Blackstar rocket launcher (Dracos warhead)', 'Heavy - Large Blast - Ignores Cover', '30"', '1', '4', '-1', 'D3', 10),
    (1, 'Blackstar cluster launcher (Frag cluster)', 'Bomb - Large Blast', '-', '1', '4', '0', 'D3+1', 10),
    (1, 'Blackstar cluster launcher (Infernus cluster)', 'Bomb - Blast - Ignores Cover', '-', '1', '5', '-2', 'D3', 10),
    (1, 'Bellicatus missile array (Frag)', 'Heavy - Blast', '48"', '1', '4', '0', '1', 5),
    (1, 'Bellicatus missile array (Icarus)', 'Heavy - Anti-Flyer', '48"', '1', '8', '-1', '2', 10),
    (1, 'Bellicatus missile array (Krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (1, 'Repulsor defensive array', 'Assault - Blast', '18"', '4', '5', '-1', '1', 20),
    (1, 'Icarus rocket pod', 'Heavy - Anti-Flyer - Indirect Fire', '24"', '1', '8', '-1', '2', 10),
    (1, 'Exitus pistol', 'Pistol - Sniper', '12"', '3', '5', '-2', '3', 10),
    (1, 'Exitus rifle', 'Heavy - Sniper', '48"', '1', '7', '-3', 'D3+3', 20),
    (1, 'Animus speculum', 'Assault - Psy-Shock - Precision Shots - Anti-Psyker - Absorbed Warp Charge', '24"', 'X', '5', '-2', 'D3', 20),
    (1, 'Executioner (Needle pistol)', 'Pistol - Poisoned (2+) - Anti-Infantry', '12"', '4', '2', '0', '1', 10),
    (1, 'Executioner (Bolt pistol)', 'Pistol', '12"', '4', '4', '0', '1', 5),
    (1, 'Neural shredder', 'Pistol - Ignores Cover - Neural Shock', 'Template', '1', '1', '-4', 'D3', 15),
    (2, 'Plague bolt pistol', 'Pistol - Lethal Hits', '12"', '1', '4', '0', '1', 0),
    (2, 'Inferno bolt pistol', 'Pistol', '12"', '1', '4', '-1', '1', 0),
    (2, 'Cultist firearm', 'Pistol', '12"', '1', '3', '0', '1', 0),
    (2, 'Bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (2, 'Boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Plague boltgun', 'Rapid Fire 1 - Lethal Hits', '24"', '2', '4', '0', '1', 0),
    (2, 'Inferno boltgun', 'Rapid Fire 1', '24"', '2', '4', '-1', '1', 0),
    (2, 'Twin boltgun', 'Rapid Fire 1 - Twin-linked', '24"', '2', '4', '0', '1', 5),
    (2, 'Hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 15),
    (2, 'Twin hurricane boltgun', 'Rapid Fire 6 - Twin-linked', '24"', '6', '4', '0', '1', 20),
    (2, 'Heavy bolter', 'Heavy - Sustained Hit 1', '36"', '3', '5', '-1', '2', 10),
    (2, 'Twin heavy bolter', 'Heavy - Twin-linked - Sustained Hit 1', '36"', '3', '5', '-1', '2', 15),
    (2, 'Combi-bolter', 'Assault - Rapid Fire 2', '24"', '2', '4', '0', '1', 0),
    (2, 'Inferno combi-bolter', 'Assault - Rapid Fire 2', '24"', '2', '4', '-1', '1', 0),
    (2, 'Warpflame pistol', 'Pistol - Ignores Cover', 'Template', '1', '3', '-1', '1', 0),
    (2, 'Flamer', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 10),
    (2, 'Combi-flamer (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-flamer (Flamer)', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 10),
    (2, 'Warpflamer', 'Assault - Ignores Cover', 'Template', '1', '4', '-1', '1', 10),
    (2, 'Plague belcher', 'Assault - Ignores Cover - Lethal Hits - Anti-Infantry', 'Template', '1', '4', '0', '1', 0),
    (2, 'Plague spewer', 'Assault - Ignores Cover - Lethal Hits - Anti-Infantry', 'Template', '1', '5', '-1', '1', 10),
    (2, 'Plaguespitter', 'Assault - Ignores Cover - Anti-Infantry', 'Template', '1', '6', '-1', '1', 15),
    (2, 'Plaguespurt gauntlet', 'Pistol - Ignores Cover - Lethal Hits', 'Template', '1', '3', '0', '1', 0),
    (2, 'Baleflamer', 'Assault - Ignores Cover', 'Template', '2', '6', '-1', 'D3', 10),
    (2, 'Twin heavy flamer', 'Assault - Ignores Cover - Twin-linked', 'Template', '1', '5', '-1', '2', 15),
    (2, 'Fire of Tzeentch (Blue fire)', 'Assault - Ignores Cover - Psychic', '18"', '3', '9', '-3', '3', 15),
    (2, 'Fire of Tzeentch (Pink fire)', 'Assault - Ignores Cover - Psychic', 'Template', '1', '5', '-1', '2', 10),
    (2, 'Flickering flames', 'Assault - Ignores Cover - Psychic', 'Template', '1', '4', '-1', '2', 10),
    (2, 'Burning roar', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 5),
    (2, 'Meltagun', 'Assault - Melta', '12"', '1', '9', '-4', 'D6', 10),
    (2, 'Combi-melta (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-melta (Meltagun)', 'Assault - Melta', '12"', '1', '9', '-4', 'D6', 10),
    (2, 'Multi-melta', 'Heavy - Melta', '18"', '2', '9', '-4', 'D6', 20),
    (2, 'Twin multi-melta', 'Heavy - Twin-linked - Melta', '18"', '2', '9', '-4', 'D6', 25),
    (2, 'Plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (2, 'Plasma pistol (Supercharge)', 'Pistol - Gets Hot', '12"', '1', '8', '-3', '2', 5),
    (2, 'Infected plasma pistol (Standard)', 'Pistol - Sustained Hit D3', '12"', '1', '7', '-2', '1', 5),
    (2, 'Infected plasma pistol (Supercharge)', 'Pistol - Gets Hot - Sustained Hit D3', '12"', '1', '8', '-3', '2', 5),
    (2, 'Plasma gun (Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (2, 'Plasma gun (Supercharge)', 'Rapid Fire 1 - Gets Hot', '24"', '1', '8', '-3', '2', 10),
    (2, 'Combi-plasma (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-plasma (Plasma gun Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (2, 'Combi-plasma (Plasma gun Supercharge)', 'Rapid Fire 1 - Gets Hot', '24"', '1', '8', '-3', '2', 10),
    (2, 'Plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (2, 'Plasma cannon (Supercharge)', 'Heavy - Gets Hot - Blast', '36"', '1', '8', '-3', '2', 10),
    (2, 'Twin plasma cannon (Standard)', 'Heavy - Twin-linked', '36"', '1', '7', '-2', '1', 10),
    (2, 'Twin plasma cannon (Supercharge)', 'Heavy - Gets Hot - Twin-linked - Blast', '36"', '1', '8', '-3', '2', 15),
    (2, 'Heavy plasma cannon (Standard)', 'Heavy - Blast', '36"', 'D3', '7', '-2', '1', 15),
    (2, 'Heavy plasma cannon (Supercharge)', 'Heavy - Gets Hot - Large Blast', '36"', 'D3', '8', '-3', '2', 15),
    (2, 'Twin heavy plasma cannon (Standard)', 'Heavy - Twin-linked - Blast', '36"', 'D3', '7', '-2', '1', 15),
    (2, 'Twin heavy plasma cannon (Supercharge)', 'Heavy - Gets Hot - Twin-linked - Large Blast', '36"', 'D3', '8', '-3', '2', 20),
    (2, 'Heavy stubber', 'Rapid Fire 3', '36"', '4', '4', '0', '1', 5),
    (2, 'Reaper autocannon', 'Heavy - Twin-linked - Devastating Wounds - Sustained Hit 1', '36"', '4', '7', '-1', '1', 15),
    (2, 'Hades autocannon', 'Heavy - Pinning', '36"', '6', '8', '-1', '2', 25),
    (2, 'Predator autocannon', 'Heavy - Rapid Fire 2', '48"', '4', '9', '-1', '3', 30),
    (2, 'Predator twin lascannon', 'Heavy - Twin-linked', '48"', '1', '14', '-3', 'D6+1', 30),
    (2, 'Lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 20),
    (2, 'Twin lascannon', 'Heavy - Twin-linked', '48"', '1', '12', '-3', 'D6+1', 25),
    (2, 'Assault cannon', 'Heavy - Devastating Wounds - Rending', '24"', '6', '6', '0', '1', 15),
    (2, 'Twin assault cannon', 'Heavy - Devastating Wounds - Rending - Twin-linked', '24"', '6', '6', '0', '1', 20),
    (2, 'Defiler cannon', 'Ordnance - Large Blast', '72"', '1', '10', '-3', 'D6+3', 30),
    (2, 'Harvester cannon (Solid shells)', 'Heavy', '48"', '3', '10', '-1', '3', 20),
    (2, 'Harvester cannon (Flakk shells)', 'Heavy - Sky Fire', '48"', '3', '7', '-2', '3', 20),
    (2, 'Skull cannon', 'Heavy - Blast', '48"', '2', '9', '-1', 'D3+1', 25),
    (2, 'Bubotic defiler cannon', 'Ordnance - Large Blast - Lethal Hits', '72"', '1', '10', '-3', 'D6+3', 35),
    (2, 'Soulburner', 'Assault - Blast - Rending', '24"', '2', '5', '-2', '1', 20),
    (2, 'Fatecaster greatbow', 'Assault - Rapid Fire 1 - Lethal Hits - Precision Shots', '30"', '1', '5', '-1', '2', 20),
    (2, 'Coruscating pink flames', 'Assault - Psychic', '18"', '2', '4', '-1', '1', 0),
    (2, 'Coruscating blue flames', 'Assault - Psychic', '18"', '3', '3', '-1', '1', 0),
    (2, 'Coruscating yellow flames', 'Assault - Psychic', '18"', '4', '2', '-1', '1', 0),
    (2, 'Phosphex bombs', 'Assault - Blast - Poisoned (3+) - Crawling Fire - Lingering Death', '6"', '1', '8', '-4', 'D3', 0),
    (2, 'Blight grenades', 'Assault - Blast - Poisoned (4+)', '8"', '1', '4', '0', '1', 5),
    (2, 'Blight launcher', 'Assault - Lethal Hits', '24"', '2', '6', '-1', '2', 10),
    (2, 'Blightreaper cannon', 'Heavy - Lethal Hits', '36"', '4', '7', '-2', '1', 25),
    (2, 'Missile launcher (Frag)', 'Heavy - Blast', '48"', '1', '4', '0', '1', 10),
    (2, 'Missile launcher (Krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (2, 'Stormstrike missile launcher', 'Heavy - Concussive - Lethal Hits - One Use Only', '48"', '1', '8', '-4', 'D6', 20),
    (2, 'Skyhammer missile launcher', 'Heavy', '60"', '3', '7', '-1', 'D3', 20),
    (3, 'Shuriken pistol', 'Pistol - Assault - Bladestorm', '12"', '1', '4', '-1', '1', 0),
    (3, 'Shuriken catapult', 'Assault - Bladestorm', '18"', '1', '4', '-1', '1', 0),
    (3, 'Twin shuriken catapult', 'Assault - Twin-linked - Bladestorm', '18"', '1', '4', '-1', '1', 5),
    (3, 'Avenger shuriken catapult', 'Assault - Bladestorm - Lethal Hits', '18"', '3', '4', '-1', '1', 5),
    (3, 'Shuriken cannon', 'Heavy - Bladestorm - Sustained Hits 1', '24"', '3', '6', '-1', '2', 5),
    (3, 'Twin shuriken cannon', 'Heavy - Twin-linked - Bladestorm - Sustained Hits 1', '24"', '3', '6', '-1', '2', 10),
    (3, 'Singing spear', 'Assault - Psychic - Fleshbane', '12"', '1', '9', '-2', '3', 15),
    (3, 'Dragon fusion gun', 'Assault - Melta', '12"', '1', '9', '-4', 'D6', 15),
    (3, 'Firepike', 'Assault - Melta', '18"', '1', '12', '-4', 'D6', 25),
    (3, 'Bright lance', 'Heavy - Lance', '36"', '1', '12', '-3', 'D6+2', 15),
    (3, 'Ranger long rifle', 'Heavy - Sniper - Precision Shots', '36"', '1', '4', '-1', '2', 10),
    (3, 'Chainsabres', 'Pistol - Assault - Bladestorm - Sustained Hits 1', '12"', '2', '4', '-1', '1', 5),
    (3, 'Reaper launcher (Starshot)', 'Heavy - Ignores Cover', '48"', '1', '8', '-2', '2', 10),
    (3, 'Reaper launcher (Starswarm)', 'Heavy - Ignores Cover', '48"', '2', '5', '-1', '1', 10),
    (3, 'Tempest launcher', 'Heavy - Ignores Cover - Blast - Indirect Fire - Barrage', '36"', '2', '4', '-1', '2', 20),
    (3, 'Lasblaster', 'Assault - Lethal Hits', '24"', '4', '4', '-1', '1', 5),
    (3, 'Hawk’s talon', 'Assault - Lethal Hits', '24"', '4', '5', '-1', '1', 5),
    (3, 'Grenade pack', 'Assault - Barrage - Blast -Ignores Cover - Skyburst', '6"', '2', '3', '0', '1', 5),
    (3, 'Death spinner', 'Assault - Ignores Cover - Blast - Devastating Wounds - Monofilament', 'Template', '1', '4', '-1', '1', 5),
    (3, 'Star lance', 'Assault - Lance', '6"', '1', '9', '-3', '2', 10),
    (3, 'Laser lance', 'Assault - Lance', '6"', '1', '6', '-2', '2', 5),
    (3, 'Aeldari missile launcher (Starshot)', 'Heavy', '48"', '1', '10', '-2', 'D6', 15),
    (3, 'Aeldari missile launcher (Sunburst)', 'Heavy - Blast', '48"', '1', '4', '-1', '1', 10),
    (3, 'Starcannon', 'Heavy', '36"', '2', '8', '-3', '2', 15),
    (3, 'Twin starcannon', 'Heavy - Twin-linked', '36"', '2', '8', '-3', '2', 20),
    (3, 'Pulse laser', 'Heavy', '48"', '3', '9', '-2', 'D6', 20),
    (3, 'Scatter laser', 'Heavy', '36"', '6', '5', '0', '1', 10),
    (3, 'Prism cannon (Dispersed pulse)', 'Heavy - Large Blast', '60"', '2', '6', '-1', 'D3+3', 20),
    (3, 'Prism cannon (Focused lances)', 'Heavy - Blast', '60"', '2', '12', '-3', 'D6+3', 20),
    (3, 'Prism cannon (Penetrating lances)', 'Heavy - Lance', '60"', '2', '18', '-5', '6', 20),
    (3, 'Doomweaver (Dispersed)', 'Heavy - Ignores Cover - Barrage - Large Blast - Indirect Fire - Twin-linked - Devastating Wounds - Monofilament', '48"', '3', '7', '0', 'D6', 15),
    (3, 'Doomweaver (Focused)', 'Heavy - Ignores Cover', 'Template', '2', '7', '0', '2', 15),
    (3, 'Heavy D-scythe', 'Assault - Blast - Distort Scythe', '18"', '2', '20', '-4', 'D6', 25),
    (3, 'D-scythe', 'Assault - Distort Scythe', '12"', 'D3', '20', '-4', '1', 20),
    (3, 'Wraithcannon', 'Assault - Devastating Wounds', '18"', '1', '14', '-4', 'D6', 25),
    (3, 'Aeldari flamer', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 5),
    (3, 'Suncannon', 'Heavy - Blast', '48"', '2', '8', '-3', 'D6+2', 30),
    (3, 'Heavy wraithcannon', 'Assault - Blast - Devastating Wounds', '36"', 'D3', '20', '-4', '2D6', 35),
    (3, 'Splinter pistol', 'Pistol - Assault - Anti-Infantry - Poisoned (4+)', '12"', '1', '2', '0', '1', 0),
    (3, 'Splinter pods', 'Assault - Anti-Infantry - Poisoned (4+) - Twin-linked', '18"', '2', '2', '0', '1', 0),
    (3, 'Splinter rifle', 'Assault - Anti-Infantry - Poisoned (4+)', '24"', '2', '2', '0', '1', 0),
    (3, 'Splinter cannon', 'Salvo 4/6 - Anti-Infantry - Poisoned (4+) - Sustained Hits 1', '36"', '3', '3', '-1', '2', 10),
    (3, 'Dark lance', 'Heavy - Lance', '36"', '1', '12', '-3', 'D6+2', 15),
    (3, 'Shredder', 'Assault - Blast - Shred', '18"', '1', '6', '0', 'D3', 10),
    (3, 'Blast pistol', 'Pistol - Lance', '6"', '1', '8', '-3', 'D3', 5),
    (3, 'Blaster', 'Assault - Lance', '18"', '1', '8', '-4', 'D6+1', 10),
    (3, 'Heat lance', 'Assault - Heavy - Melta', '18"', '1', '14', '-4', 'D6', 10),
    (3, 'Haywire blaster', 'Heavy - Devastating Wounds - Haywire - Anti-Vehicles', '24"', '2', '3', '-1', '3', 10),
    (3, 'Sharcarbine', 'Assault - Anti-Infantry - Poisoned (4+)', '18"', '3', '2', '0', '1', 5),
    (3, 'Disintegrator cannon', 'Heavy', '36"', '3', '5', '-2', '2', 15),
    (3, 'Torment grenades launcher', 'Assault - Blast - Soulfright', '24"', '1', '1', '0', 'D3', 10),
    (4, 'Atomiser beam', 'Assault', '12"', '3', '6', '-2', '1', 15),
    (4, 'Doomsday cannon (Low power)', 'Heavy - Blast', '24"', '1', '8', '-3', 'D3+4', 20),
    (4, 'Doomsday cannon (High power)', 'Primary - Large Blast', '72"', '1', '15', '-4', 'D6+4', 25),
    (4, 'Enmitic annihilator', 'Rapid Fire 2', '18"', '2', '6', '-1', '1', 10),
    (4, 'Gauss blaster', 'Assault - Lethal Hits', '24"', '2', '5', '-1', '1', 5),
    (4, 'Gauss cannon', 'Heavy - Lethal Hits', '24"', '3', '5', '-2', '2', 15),
    (4, 'Gauss flayer', 'Rapid Fire 1 - Lethal Hits', '24"', '1', '4', '0', '1', 0),
    (4, 'Gauss flayer array', 'Salvo 5/10 - Rapid Fire 5 - Lethal Hits', '24"', '5', '4', '0', '1', 10),
    (4, 'Gauss flux arc', 'Heavy - Rapid Fire 3 - Lethal Hits', '24"', '3', '6', '-1', '1', 15),
    (4, 'Gauss reaper', 'Assault - Lethal Hits', '12"', '2', '5', '-1', '1', 5),
    (4, 'Heavy death ray', 'Heavy - Sustained Hits 3', '24"', '1', '12', '-4', 'D6+1', 20),
    (4, 'Particle beamer', 'Assault - Blast - Devastating Wounds', '18"', '2', '6', '0', 'D3', 10),
    (4, 'Particle caster', 'Pistol - Devastating Wounds', '12"', '3', '5', '0', '1', 5),
    (4, 'Particle shredder', 'Heavy - Large Blast - Devastating Wounds', '18"', '1', '7', '-1', '2', 10),
    (4, 'Particle whip', 'Ordnance - Large Blast - Devastating Wounds', '24"', '1', '8', '-1', 'D6+3', 35),
    (4, 'Plasmic lance', 'Assault', '18"', '3', '7', '-3', '2', 10),
    (4, 'Relic gauss blaster', 'Rapid Fire 2 - Lethal Hits', '24"', '2', '5', '-1', '2', 10),
    (4, 'Rod of covenant', 'Assault', '12"', '1', '5', '-2', '2', 10),
    (4, 'Scouring eye', 'Pistol - Assault', '6"', '2', '5', '-1', '1', 5),
    (4, 'Staff of light', 'Assault', '18"', '3', '5', '-2', '1', 10),
    (4, 'Synaptic disintegrator', 'Heavy - Precision Shots', '36"', '1', '5', '-2', '2', 10),
    (4, 'Tachyon arrow', 'Assault - One Use Only', '72"', '1', '16', '-5', 'D6+2', 25),
    (4, 'Tesla arc', 'Assault 3D6', '3"', '0', '4', '0', '1', 0),
    (4, 'Tesla cannon', 'Heavy - Sustained Hits 2', '24"', '4', '6', '0', '1', 10),
    (4, 'Tesla carbine', 'Assault - Sustained Hits 2', '18"', '2', '5', '0', '1', 0),
    (4, 'Tesla destructor', 'Heavy - Sustained Hits 2', '36"', '6', '8', '0', '2', 15),
    (4, 'Transdimensional beamer', 'Assault', '12"', '1', '4', '-2', '3', 10),
    (4, 'Twin tesla carbine', 'Assault - Twin-linked - Sustained Hits 2- Ignores Cover', '18"', '2', '5', '0', '1', 5),
    (4, 'Twin particle beamer', 'Assault - Twin-linked - Blast - Devastating Wounds', '18"', '2', '6', '0', 'D3', 15),
    (4, 'Twin tesla destructor', 'Heavy - Twin-linked - Sustained Hits 2', '36"', '6', '8', '0', '2', 20),
    (5, 'Kombi-skorcha (Shoota)', 'Assault - Rapid Fire 1', '18"', '2', '4', '0', '1', 0),
    (5, 'Kombi-skorcha (Skorcha)', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 5),
    (5, 'Slugga', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (5, 'Twin slugga', 'Pistol - Twin-linked', '12"', '1', '4', '0', '1', 5),
    (5, 'Twin dakkagun', 'Assault - Rapid Fire 2 - Twin-linked', '18"', '3', '5', '0', '1', 5),
    (5, 'Shoota', 'Assault - Rapid Fire 1', '18"', '2', '4', '0', '1', 0),
    (5, 'Big shoota', 'Assault - Rapid Fire 2', '36"', '3', '5', '0', '1', 5),
    (5, 'Rokkit launcha', 'Assault - Blast', '24"', '2', '9', '-2', '1', 5),
    (5, 'Burna', 'Assault - Ignores Cover', 'Template', '1', '4', '0', '1', 0),
    (5, 'Kustom mega -Blasta (Short range)', 'Pistol - Hazardous', '12"', '3', '9', '-2', 'D6', 5),
    (5, 'Kustom mega -Blasta (Medium range)', 'Assault - Hazardous', '24"', '3', '9', '-2', 'D3', 10),
    (5, 'Kustom mega -Blasta (Long range)', 'Heavy - Hazardous - Blast', '36"', '3', '9', '-2', '1', 15),
    (5, 'Deffgun', 'Heavy - Rapid Fire 1', '48"', '2', '8', '-1', '2', 10),
    (1, 'Infernus', 'Assault - One Use Only - Master-crafted', '18"', '2', '8', '-5', 'D6', 0),
    (1, 'The Spear of Telesto', 'Assault - Instant Death - Armourbane - Wrath of Angels - Master-crafted', '12"', '1', '7', '-5', 'D3+3', 0),
    (1, 'The Furnaces Heart', 'Assault - Devastating Wounds - Lethal Hits - Line of Effect - Master-crafted', '18"', '1', '6', '-4', 'D6', 0),
    (1, 'The Ardent Blade', 'Assault - Ignores Cover - Master-crafted', 'Template', '1', '6', '-2', '1', 0),
    (2, 'The Widowmakers', 'Assault - Fatal Precision - Lethal Hits - Sustained Hit 2 - Master-crafted', '12"', '3', '4', '-1', '2', 0),
    (2, 'The Lantern', 'Pistol - Assault - Sunder - Sustained Hit D3 - Master-crafted', '18"', '1', '9', '-4', '.3', 0),
    (3, 'The Wailing Doom', 'Assault - Master-crafted', '12"', '1', '16', '-4', 'D6+2', 0),
    (3, 'The Silent Death', 'Assault - Master-crafted', '12"', '6', '6', '-2', '1', 0),
    (3, 'Voidbringer', 'Heavy - Master-crafted', '48"', '1', '6', '-3', '3', 0),
    (3, 'The Parasite’s Kiss', 'Pistol - Master-crafted - Poisoned (2+) - Soul-leech', '12"', '1', '2', '-1', '2', 0),
    (1, 'Castigation', 'Psychic - Precision Shots - Devastating Wounds - Anti-Character', '18"', '1', '8', '-2', '3', 0),
    (1, 'Cleanse (Witchfire)', 'Psychic', '24"', 'D6', '5', '-1', 'D3', 0),
    (1, 'Cleanse (Focused Witchfire)', 'Psychic - Devastating Wounds - Hazardous', '24"', 'D6', '6', '-2', 'D3', 0),
    (1, 'Smite (Witchfire)', 'Psychic', '12"', '5', '5', '-2', '2', 0),
    (1, 'Smite (Focused Witchfire)', 'Psychic - Devastating Wounds - Hazardous', '12"', '5', '6', '-2', '2', 0),
    (2, 'Infernal Gaze (Witchfire)', 'Psychic', '24"', 'D6', '5', '-1', 'D3', 0),
    (2, 'Infernal Gaze (Focused Witchfire)', 'Psychic - Hazardous - Devastating Wounds', '24"', 'D6', '6', '-2', 'D3', 0),
    (2, 'Rotwind', 'Psychic - Blast - Devastating Wounds - Lethal Hits', '18"', '1', '7', '-2', 'D6+3', 0),
    (2, 'Plague Wind (Witchfire)', 'Psychic - Ignores Cover - Lethal Hits', 'Template', '2', '4', '-1', 'D6', 0),
    (2, 'Plague Wind (Focused Witchfire)', 'Psychic - Hazardous - Ignores Cover - Lethal Hits', 'Template', '2', '6', '-2', 'D6+3', 0),
    (2, 'Psyfire serpenta', 'Psychic - Assault - Soul Blaze', '15"', 'D3', '8', '-4', '1', 0),
    (2, 'Gaze of Magnus', 'Psychic - Devastating Wounds', '24"', '3D3', '9', '-2', '3', 0),
    (2, 'Tzeentch’s Firestorm', 'Psychic - Blast', '24"', '2', '5', '-1', 'D6+3', 0),
    (2, 'Psychic Stalk', 'Psychic - Precision Shots', '18"', '1', '6', '-1', 'D6', 0),
    (2, 'Arcane Fire', 'Psychic - Ignores Cover', 'Template', '1', '6', '-2', '1', 0),
    (2, 'Astral Blast', 'Psychic - Blast - Devastating Wounds', '18"', 'D3', '6', '-2', '1', 0),
    (2, 'Warpsmite', 'Psychic - Pistol - Anti-Infantry - Devastating Wounds', '18"', '1', '4', '-1', '1', 0),
    (2, 'Mutating Orbs', 'Psychic - Blast - Devastating Wounds', '18"', '1', '9', '0', 'D3+1', 0),
    (2, 'Infernal Gateway (Witchfire)', 'Psychic - Blast - Indirect Fire', '24"', 'D6+3', '9', '-2', 'D3', 0),
    (2, 'Infernal Gateway (Focused Witchfire)', 'Psychic - Blast - Indirect Fire - Hazardous', '24"', 'D3+1', '9', '-3', 'D3', 0),
    (2, 'Infernal Flames (Witchfire)', 'Psychic - Ignores Cover', 'Template', '1', '6', '-1', '1', 0),
    (2, 'Infernal Flames (Focused Witchfire)', 'Psychic - Ignores Cover - Hazardous', 'Template', 'D3', '6', '-1', 'D3+1', 0),
    (2, 'Infernal cannon', 'Psychic', '24"', '6', '5', '-1', '2', 0),
    (2, 'Arcane Fireball (Witchfire)', 'Psychic', '18"', '3', '5', '-1', 'D3', 0),
    (2, 'Arcane Fireball (Focused Witchfire)', 'Psychic - Hazardous - Devastating wounds', '18"', '3', '6', '-2', 'D3', 0),
    (2, 'Warp Gaze', 'Psychic - Blast', '48"', '1', '12', '-2', '3', 0),
    (2, 'Hellfire Breath', 'Psychic - Ignores Cover', 'Template', '1', '5', '-1', '1', 0),
    (2, 'Torrent of burning blood', 'Psychic - Ignores Cover', 'Template', '1', '5', '-1', '2', 0),
    (3, 'Swirling soul energy', 'Psychic - Ignores Cover', 'Template', '2', '7', '-1', '2', 0),
    (3, 'Storm of Whispers', 'Psychic - Ignores Cover - Anti-Infantry - Devastating Wounds', 'Template', '1', '2', '-2', '3', 0),
    (3, 'Eldritch Storm', 'Psychic - Blast', '24"', '1', '6', '-2', 'D6+2', 0),
    (3, 'Destructor', 'Psychic - Ignores Cover', 'Template', '1', '5', '-1', '1', 0),
    (1, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Combat knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Combat blade', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (1, 'Paired combat blade', 'Melee - Sustained Hits 1', 'Melee', 'User', 'User', '-1', '1', 10),
    (1, 'Astartes chainsword', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (1, 'Force axe', 'Melee - Unwieldy - Psychic', 'Melee', 'User', '+2', '-2', 'D3', 15),
    (1, 'Force maul', 'Melee - Concussive - Psychic', 'Melee', 'User', '+3', '-1', 'D3', 15),
    (1, 'Force sword', 'Melee - Psychic', 'Melee', 'User', '+1', '-3', 'D3', 15),
    (1, 'Power axe', 'Melee - Unwieldy', 'Melee', 'User', '+2', '-2', '1', 10),
    (1, 'Power maul', 'Melee - Concussive', 'Melee', 'User', '+3', '-1', '1', 10),
    (1, 'Power sword', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (1, 'Crozius Arcanum', 'Melee - Concussive', 'Melee', 'User', '+2', '-1', '2', 10),
    (1, 'Relic blade', 'Melee - Devastating Wounds - Two Handed','Melee', '+1', '+1', '-2', '2', 10),
    (1, 'Executioner relic blade', 'Melee - Concussive','Melee', '+1', '+3', '-2', '2', 15),
    (1, 'Xenophase blade', 'Melee - Devastating Wounds - Molecular Realignment Field','Melee', '+1', '+1', '-3', '3', 20),
    (1, 'Life-draining touch', 'Melee - Precision Strikes - Devastating Wounds - Anti-Psyker', 'Melee', 'User', 'User', '-2', '2', 10),
    (1, 'Neuro gauntlet', 'Melee - Shred - Fleshbane - Anti-Infantry', 'Melee', '-1', '+1', '0', '2', 10),
    (1, 'Phase sword', 'Melee - Devastating Wounds - Lethal Hits','Melee', 'User', '+1', '-4', '1', 15),
    (1, 'Poison Blades', 'Melee - Rending - Poisoned (3+) - Anti-Infantry','Melee', 'User', '+1', '0', '2', 10),
    (1, 'Arc scourge', 'Melee - Anti-Vehicles - Extra Attacks - Devastating Wounds','Melee', 'User', '+1', '-1', '1', 5),
    (1, 'Arc maul', 'Melee - Anti-Vehicles - Haywire - Concussive','Melee', 'User', '+3', '-2', '2', 15),
    (1, 'Taser goad', 'Melee - Concussive - Sustained Hit 2','Melee', 'User', '+3', '0', '2', 10),
    (1, 'Mechadendrite hive', 'Melee - Extra Attacks','Melee', '2D6', 'User', '0', '1', 5),
    (1, 'Servo-arm', 'Melee - Specialist - Unwieldy - Extra Attacks', 'Melee', '1', 'x2', '-2', '3', 15),
    (1, 'Omnissian power axe', 'Melee - Unwieldy', 'Melee', 'User', '+2', '-2', '2', 15),
    (1, 'Crawls omnissian axe', 'Melee - Unwieldy', 'Melee', 'User', '+4', '-2', '2', 20),
    (1, 'Vigil Spear (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', 'D3', 10),
    (1, 'Vigil Spear (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (1, 'Power fist', 'Melee - Specialist - Unwieldy', 'Melee', '-1', 'x2', '-2', '2', 15),
    (1, 'Lightning claw', 'Melee - Shred - Specialist', 'Melee', 'User', '+1', '-2', '2', 10),
    (1, 'Twin lightning claw', 'Melee - Twin-linked - Shred - Specialist', 'Melee', 'User', '+1', '-2', '2', 15),
    (1, 'Chainfist', 'Melee - Specialist - Unwieldy - Armourbane - Anti-Vehicles', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Thunder hammer', 'Melee - Concussive - Specialist - Unwieldy - Anti-Vehicles', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Heavy thunder hammer', 'Melee - Concussive - Specialist - Unwieldy - Devastating Wounds - Two Handed - Pulverise', 'Melee', '-1', 'x2', '-4', '3', 25),
    (1, 'Boltstorm', 'Melee -  - Specialist - Unwieldy', 'Melee', '-2', 'x2', '-2', '3', 20),
    (1, 'Kastelan fist', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (1, 'Invictor fist', 'Melee', 'Melee', '+1', 'x2', '-2', '3', 20),
    (1, 'Dreadnought combat weapon', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (1, 'Dreadnought chainfist', 'Melee - Armourbane - Anti-Vehicles', 'Melee', '-1', 'x2', '-2', '3', 25),
    (1, 'Dreadnought lightning claw', 'Melee - Shred', 'Melee', '+1', '+1', '-2', '3', 15),
    (1, 'Thunderstrike gauntlet (Strike)', 'Melee - Colossal', 'Melee', 'User', 'x2', '-3', '8', 25),
    (1, 'Thunderstrike gauntlet (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '3', 25),
    (1, 'Reaper chaincleaver (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 15),
    (1, 'Reaper chaincleaver (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '1', 15),
    (1, 'Reaper chainsword (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', '6', 20),
    (1, 'Reaper chainsword (Sweep)', 'Melee', 'Melee', 'x3', 'User', '-3', '2', 25),
    (2, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Combat knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Improvised weapon', 'Melee - Lethal Hits', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Chakhal flails', 'Melee - Sustained Hits 1', 'Melee', 'User', '+1', '0', '1', 0),
    (2, 'Chakhal mauler', 'Melee - Concussive', 'Melee', 'User', '+2', '-1', '2', 0),
    (2, 'Dishonoured chainblades', 'Melee', 'Melee', '+1', '+1', '0', '1', 0),
    (2, 'Skullsmasher', 'Melee - Shred', 'Melee', '+2', '+1', '-1', '2', 0),
    (2, 'Pink claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Blue claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Yellow claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Plague knife', 'Melee - Lethal Hits', 'Melee', 'User', 'User', '0', '1', 5),
    (2, 'Astartes chainsword', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (2, 'Berzerker chainsword', 'Melee - Extra Attacks', 'Melee', 'User', 'User', '-1', '1', 5),
    (2, 'Berzerker chainaxe', 'Melee - Unwieldy - Devastating Wounds', 'Melee', 'User', 'User', '-2', '2', 10),
    (2, 'Nostraman chainglaive', 'Melee - Two Handed - Rending - Devastating Wounds', 'Melee', 'User', '+1', '0', '2', 0),
    (2, 'Hideous Mutation', 'Melee', 'Melee', 'User', 'User', '-1', '2', 5),
    (2, 'Force axe', 'Melee - Unwieldy - Psychic', 'Melee', 'User', '+2', '-2', 'D3', 15),
    (2, 'Force maul', 'Melee - Concussive - Psychic', 'Melee', 'User', '+3', '-1', 'D3', 15),
    (2, 'Force sword', 'Melee - Psychic', 'Melee', 'User', '+1', '-3', 'D3', 15),
    (2, 'Prosperine khopesh', 'Melee - Psychic', 'Melee', 'User', '+1', '-3', '1', 15),
    (2, 'Force stave', 'Melee - Psychic - Concussive', 'Melee', 'User', '+3', '-1', '3', 15),
    (2, 'Shaman stave', 'Melee - Psychic - Concussive', 'Melee', 'User', '+2', '-1', 'D3', 10),
    (2, 'Corrupted staff', 'Melee - Lethal Hits - Psychic', 'Melee', 'User', '+2', '-1', 'D3', 15),
    (2, 'Power axe', 'Melee - Unwieldy', 'Melee', 'User', '+2', '-2', '1', 10),
    (2, 'Axe of dismemberment', 'Melee - Unwieldy Two Handed - Devastating Wounds', 'Melee', 'User', '+3', '-2', '2', 15),
    (2, 'Power maul', 'Melee - Concussive', 'Melee', 'User', '+3', '-1', '1', 10),
    (2, 'Power sword', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (2, 'Balesword', 'Melee - Lethal Hits', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Blade of blood', 'Melee - Specialist - Unwieldy', 'Melee', 'User', '+1', '-2', '3', 10),
    (2, 'Attendant hellblades', 'Melee - Extra AttacksSoul', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Hellblade', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Divining spear', 'Melee - Lance - Precision Strikes', 'Melee', 'User', '+2', '-2', '1', 10),
    (2, 'Exalted weapon', 'Melee', 'Melee', '+2', '+1', '-2', '2', 20),
    (2, 'Daemon blade', 'Melee - Devastating Wounds - Hazardous', 'Melee', '+1', '+3', '-3', 'D3', 25),
    (2, 'Bubotic weapon', 'Melee - Lethal Hits', 'Melee', 'User', '+1', '-2', '1', 15),
    (2, 'Bubotic axe & Mace of Contagion', 'Melee - Unwieldy - Lethal Hits', 'Melee', '+1', '+1', '-2', '2', 20),
    (2, 'Heavy plague weapon', 'Melee - Lethal Hits', 'Melee', '-1', 'x2', '-2', '2', 25),
    (2, 'Cursed plague bell', 'Melee - Lethal Hits', 'Melee', '+1', 'User', '0', '2', 5),
    (2, 'Manreaper (Strike)', 'Melee - Lethal Hits', 'Melee', 'User', 'x2', '-2', '3', 10),
    (2, 'Manreaper (Sweep)', 'Melee - Lethal Hits', 'Melee', 'x2', 'User', '-1', '1', 10),
    (2, 'Plagueblade (Strike)', 'Melee - Lethal Hits', 'Melee', 'User', 'x2', '-2', '3', 10),
    (2, 'Plagueblade (Sweep)', 'Melee - Lethal Hits', 'Melee', 'x2', 'User', '0', '1', 10),
    (2, 'Plague probe', 'Melee - Lethal Hits', 'Melee', 'User', 'User', '-1', '1', 5),
    (2, 'Greater plague probe', 'Melee - Lethal Hits', 'Melee', 'User', 'User', '-2', '1', 5),
    (2, 'Bile maw', 'Melee - Lethal Hits', 'Melee', 'User', '+2', '-1', '1', 5),
    (2, 'Great axe of Khorne (Strike)', 'Melee - Unwieldy - Colossal - Specialist - Decapiting Blow', 'Melee', 'User', 'x2', '-4', 'D6+2', 30),
    (2, 'Great axe of Khorne (Sweep)', 'Melee - Unwieldy', 'Melee', 'x2', 'User', '-2', '2', 25),
    (2, 'Tzaangor blades', 'Melee - Extra Attacks', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Tzaangor heavy blades', 'Melee - Two Handed', 'Melee', '-1', '+2', '-1', '1', 5),
    (2, 'Flamer mouths', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Lamprey bites', 'Melee - Extra Attacks - Armourbane', 'Melee', 'User', 'User', '-2', '2', 5),
    (2, 'Juggernaut bladed horn', 'Melee - Lance - Extra Attacks', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Soul-rending fangs', 'Melee - Precision Strikes', 'Melee', 'User', 'User', '-1', '2', 5),
    (2, 'Gore-denched fangs', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Biting maw', 'Melee - Lethal Hits', 'Melee', 'User', 'User', '0', '2', 0),
    (2, 'Power fist', 'Melee - Specialist - Unwieldy', 'Melee', '-1', 'x2', '-2', '2', 15),
    (2, 'Bubotic power fist', 'Melee - Lethal Hits', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Lightning claw', 'Melee - Shred - Specialist', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Twin lightning claw', 'Melee - Twin-linked - Shred - Specialist', 'Melee', 'User', '+1', '-2', '2', 15),
    (2, 'Warp claws', 'Melee - Twin-linked - Shred - Specialist', 'Melee', '+1', '+1', '-2', '1', 10),
    (2, 'Warpclaw', 'Melee - Extra Attacks', 'Melee', '+1', 'User', '-1', '2', 0),
    (2, 'Warpsword', 'Melee - Extra Attacks', 'Melee', 'User', 'User', '-2', 'D6', 5),
    (2, 'Daemons claw', 'Melee', 'Melee', 'User', 'user', '0', '1', 0),
    (2, 'Mutating warpblade (Strike)', 'Melee - Specialist - Psychic - Warp Mutation', 'Melee', 'User', 'x2', '-2', '3', 25),
    (2, 'Mutating warpblade (Sweep)', 'Melee - Specialist - Psychic - Warp Mutation', 'Melee', 'x2', 'User', '0', '1', 25),
    (2, 'Chainfist', 'Melee - Specialist - Unwieldy - Armourbane - Anti-Vehicles', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Thunder hammer', 'Melee - Concussive - Specialist - Unwieldy - Devastating Wounds', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Heavy thunder hammer', 'Melee - Concussive - Specialist - Unwieldy - Devastating Wounds', 'Melee', '-1', 'x2', '-4', '3', 25),
    (2, 'Dreadnought combat weapon', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (2, 'Dreadnought lightning claw', 'Melee - Shred', 'Melee', '+1', '+1', '-2', '3', 15),
    (2, 'Dreadnought chainfist', 'Melee - Armourbane - Anti-Vehicles', 'Melee', '-1', 'x2', '-2', '3', 25),
    (2, 'Helbrute fist', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (2, 'Defiler claw', 'Melee', 'Melee', 'User', 'x2', '-2', 'D3+3', 25),
    (2, 'Defiler scourge', 'Melee - Extra Attacks', 'Melee', '+2', '+4', '-1', '2', 20),
    (2, 'Bubotic defiler scourge', 'Melee - Extra Attacks - Lethal Hits', 'Melee', '+2', '+4', '-1', '2', 25),
    (3, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (3, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (3, 'Witchblade', 'Melee - Psychic - Anti-Infantry - Armourbane - Fleshbane', 'Melee', 'User', '+1', '-2', '2', 15),
    (3, 'Singing spear (Strike)', 'Melee - Psychic - Anti-Infantry - Armourbane - Fleshbane', 'Melee', 'User', 'x2', '-2', '3', 15),
    (3, 'Singing spear (Sweep)', 'Melee - Psychic - Anti-Infantry - Armourbane - Fleshbane', 'Melee', 'x2', 'User', '-1', '1', 15),
    (3, 'Witchstaff', 'Melee - Psychic - Anti-Infantry - Armourbane - Fleshbane - Soul Blaze', 'Melee', 'User', '+2', '0', 'D3', 10),
    (3, 'Aeldari power sword', 'Melee', 'Melee', 'User', '+1', '-2', '1', 10),
    (3, 'Star glaive (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '2', 15),
    (3, 'Star glaive (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 15),
    (3, 'Banshee blade', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (3, 'Mirrorswords', 'Melee - Sustained Hits 1', 'Melee', '+1', '+1', '-3', '1', 10),
    (3, 'Executioner', 'Melee - Two Handed', 'Melee', 'User', '+2', '-2', '2', 10),
    (3, 'Diresword', 'Melee - Devastating Wounds', 'Melee', 'User', '+1', '-2', '1', 10),
    (3, 'Scorpion chainsword', 'Melee - Sustained hits 1', 'Melee', '+1', '+1', '-1', '2', 10),
    (3, 'Chainsabres', 'Melee - Sustained hits 1 - Rending', 'Melee', 'User', '+1', '0', '1', 5),
    (3, 'Powerblades', 'Melee', 'Melee', '+1', '+1', '-2', '1', 10),
    (3, 'Star lance', 'Melee - Lance', 'Melee', '+1', 'User', '-3', '2', 5),
    (3, 'Laser lance', 'Melee - Lance', 'Melee', 'User', 'User', '-2', '2', 5),
    (3, 'Ghostaxe', 'Melee - Unwieldy', 'Melee', 'User', '+2', '-2', '2', 10),
    (3, 'Ghostswords', 'Melee', 'Melee', '+1', '+1', '-2', '1', 10),
    (3, 'Wraithbone fists', 'Melee', 'Melee', 'User', 'User', '-2', '2', 10),
    (3, 'Ghostglaive (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', 'D6+1', 15),
    (3, 'Ghostglaive (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '2', 10),
    (3, 'Titanic ghostglaive (Strike)', 'Melee - Master-crafted', 'Melee', 'User', 'x2', '-3', '6', 20),
    (3, 'Titanic ghostglaive (Sweep)', 'Melee - Master-crafted', 'Melee', 'x2', 'User', '-2', '2', 15),
    (3, 'Demiklaives (Single-blade)', 'Melee - Devastating Wounds - Two Handed', 'Melee', 'User', 'x2', '-2', '2', 15),
    (3, 'Demiklaives (Dual-blade)', 'Melee - Twin-linked', 'Melee', 'x2', 'User', '-1', '1', 10),
    (3, 'Klaive', 'Melee - Devastating Wounds - Two Handed', 'Melee', 'User', '+1', '-2', '2', 15),
    (3, 'Drukhari power blade', 'Melee', 'Melee', '+1', 'User', '-2', '1', 10),
    (3, 'Agoniser', 'Melee - Poisoned (4+) - Anti-Infantry', 'Melee', '+1', 'User', '-1', '1', 5),
    (3, 'Hekatarii blades', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (3, 'Razorflail', 'Melee - Twin-li,ked - Specialist - Blade Whip', 'Melee', 'User', 'User', '-2', '1', 10),
    (3, 'Mindphase Gauntlet', 'Melee - Concussive - Twin-linked', 'Melee', 'User', 'User', '-1', '1', 10),
    (3, 'Shardnet & Impaler', 'Melee - Ritual Pair', 'Melee', 'User', 'User', '-1', '2', 10),
    (3, 'Impaler', 'Melee - Impale', 'Melee', 'User', 'User', '-1', '1', 5),
    (3, 'Hellglaive', 'Melee - Two Handed - Sustained Hits 1', 'Melee', 'User', '+1', '-1', '2', 10),
    (3, 'Stunclaw', 'Melee - Snatched', 'Melee', 'User', '+1', '0', '1', 0),
    (3, 'Bladevanes', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Automaton claws', 'Melee', 'Melee', 'User', '+2', '-2', '2', 15),
    (4, 'Feeder mandibles', 'Melee - Lethal Hits', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Flensing claw', 'Melee - Rending', 'Melee', 'x2', 'User', '-1', '1', 10),
    (4, 'Hyperphase glaive', 'Melee', 'Melee', 'User', '+2', '-2', 'D3', 10),
    (4, 'Hyperphase harvester', 'Melee', 'Melee', 'User', '+4', '-3', '3', 20),
    (4, 'Hyperphase reap-blade', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (4, 'Hyperphase sword', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (4, 'Hyperphase threshers', 'Melee', 'Melee', '+1', 'User', '-1', '1', 10),
    (4, 'Plasmic lance', 'Melee', 'Melee', 'User', '+3', '-3', '2', 10),
    (4, 'Portal of exile', 'Melee', 'Melee', 'User', 'User', '-2', '3', 15),
    (4, 'Reanimator’s claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Rod of covenant', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (4, 'Staff of light', 'Melee', 'Melee', 'User', '+1', '-2', '1', 10),
    (4, 'Stalker’s forelimbs (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 10),
    (4, 'Stalker’s forelimbs (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (4, 'Vicious claws', 'Melee', 'Melee', 'User', '+4', '-1', '2', 10),
    (4, 'Voidblade', 'Melee - Rending - Entropic Strike', 'Melee', 'User', 'x2', '-3', '2', 15),
    (4, 'Whip coils', 'Melee', 'Melee', 'x2', 'User', '0', '1', 5),
    (5, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (5, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (5, 'Power Klaw', 'Melee', 'Melee', 'User', 'x2', '-2', '2', 15),
    (5, 'Attack squig', 'Melee - Extra Attacks', 'Melee', 'User', 'User', '0', '1', 15),
    (5, 'Choppa', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (5, 'Big choppa', 'Melee - Two Handed', 'Melee', '-1', '+3', '-1', '2', 5),
    (5, 'Cuttin’flames', 'Melee', 'Melee', 'User', 'User', '-2', '1', 5),
    (5, 'Wreckin’ball', 'Melee - Concussive', 'Melee', '+D3', '+5', '-2', 'D3+3', 15),
    (1, 'Black Sword (Strike)', 'Melee - Precision Strikes - Master-crafted', 'Melee', 'User', 'x2', '-3', '3', 0),
    (1, 'Black Sword (Sweep)', 'Melee - Master-crafted', 'Melee', 'x2', 'User', '-2', '1', 0),
    (1, 'The Spear of Telesto (Strike)', 'Melee - Two Handed - Instant Death - Wrath of Angels - Master-crafted', 'Melee', 'User', 'x2', '-4', 'D3+1', 0),
    (1, 'The Spear of Telesto (Sweep)', 'Melee - Two Handed - Instant Death - Wrath of Angels - Master-crafted', 'Melee', 'x2', 'User', '-3', 'D3', 0),
    (1, 'Moonsilver', 'Melee - Blind - Duellist Edge - Moonsilver - Master-crafted', 'Melee', 'User', 'User', '-3', '2', 0),
    (1, 'Dawnbringer', 'Melee - Two Handed - Concussive - Devastating Wounds - Lethal Hits - Armourbane - Instant Death - Earthshatter - Master-crafted', 'Melee', 'User', '+3', '-5', 'D3+3', 0),
    (1, 'The Ardent Blade', 'Melee - Master-crafted - Armourbane', 'Melee', '+1', '+1', '-3', '1', 0),
    (2, 'Mercy & Forgiveness', 'Melee - Shred - Murderous Strike - Specialist - Twin-linked - Lethal Hits - Devastating Wounds - Sustained Hit 2 - Master-crafted', 'Melee', 'User', '+1', '-4', 'D6', 0),
    (2, 'Claws of the Black Hunt', 'Melee - Twin-linked - Specialist - Shred - Sustained Hit 2 - Master-crafted', 'Melee', '+3', '+2', '-3', 'D3+2', 35),
    (2, 'Silence (Strike)', 'Melee - Reaping Blow - Sunder - Two Handed - Devastating Wounds - Lethal Hits - Master-crafted', 'Melee', 'User', 'x2', '-3', '4', 0),
    (2, 'Silence (Sweep)', 'Melee - Reaping Blow - Sunder - Two Handed - Devastating Wounds - Lethal Hits - Master-crafted', 'Melee', 'x3', 'User', '-1', '1', 0),
    (2, 'The Blade of Ahn-Nunurta (Strike)', 'Melee - Psychic - Master-crafted - Two Handed - Devastating Wounds', 'Melee', 'User', 'x2', '-3', '3', 0),
    (2, 'The Blade of Ahn-Nunurta (Sweep)', 'Melee - Psychic - Master-crafted - Two Handed', 'Melee', 'x2', 'User', '-1', '1', 0),
    (2, 'Black Staff of Ahriman', 'Melee - Psychic - Master-crafted', 'Melee', '+1', '+3', '-1', '3', 0),
    (2, 'Seer’s Bane', 'Melee - Master-crafted - Psychic', 'Melee', 'User', '+1', '-3', 'D3', 0),
    (2, 'Gorechild', 'Melee - Master-crafted - Armourbane - Fleshbane', 'Melee', 'User', '+2', '-2', '3', 0),
    (2, 'Staff of Tommorrow', 'Melee - Psychic - Master-crafted', 'Melee', 'User', '+2', '-2', '2D3', 0),
    (2, 'The Trickster Staff', 'Melee - Psychic - Master-crafted', 'Melee', 'User', '+1', '-1', 'D3', 0),
    (2, 'Sharp quills', 'Melee - Psychic - Master-crafted - Anti-Psyker', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'The Slayer Sword', 'Melee - Master-crafted - Decapiting Blow - Soul Blaze - Devastating Wounds - Precision Strikes', 'Melee', 'User', '+2', '-2', '3', 0),
    (3, 'The Wailing Doom (Strike)', 'Melee - Master-crafted', 'Melee', 'User', 'x2', '-4', 'D6+2', 0),
    (3, 'The Wailing Doom (Sweep)', 'Melee - Master-crafted', 'Melee', 'x2', 'User', '-2', '2', 0),
    (3, 'Vilith-zhar, the Sword of Souls (Strike)', 'Melee - Psychic - Master-crafted', 'Melee', 'User', 'x2', '-4', 'D6+1', 0),
    (3, 'Vilith-zhar, the Sword of Souls (Sweep)', 'Melee - Psychic - Master-crafted', 'Melee', 'x2', 'User', '-4', '1', 0),
    (3, 'Asu-var, the Sword of Silent Screams', 'Melee - Psychic - Master-crafted - Precision Strikes', 'Melee', 'User', 'User', '-4', '2', 0),
    (3, 'Kha-vir, the Sword of Sorrows', 'Melee - Psychic - Master-crafted - Devastating Wounds', 'Melee', 'User', 'User', '-3', '2', 0),
    (3, 'The Staff of Ulthamar', 'Melee - Psychic - Master-crafted - Anti-Infantry', 'Melee', 'User', '+2', '-1', '2', 0),
    (3, 'The Blade of Destruction (Strike)', 'Melee - Master-crafted - Shred', 'Melee', 'User', 'x2', '-3', '2', 0),
    (3, 'The Blade of Destruction (Sweep)', 'Melee - Master-crafted', 'Melee', 'x2', 'User', '-3', '1', 0),
    (3, 'The Triptych Whip', 'Melee - Master-crafted- Poisoned (2+) - Fleshbane', 'Melee', '+3', 'User', '-2', '1', 0),
    (3, 'The Executioner’s (Single-blade)', 'Melee - Master-crafted - Devastating Wounds - Two Handed', 'Melee', '+1', '+2', '-2', '3', 0),
    (3, 'The Executioner’s (Dual-blade)', 'Melee - Master-crafted - Twin-linked', 'Melee', '+3', '+1', '-2', '2', 0),
    (3, 'Lelith’s blades', 'Melee - Master-crafted - Sustained Hits 2 - Anti-Infantry', 'Melee', 'User', 'User', '-2', '1', 0)
;

-- Weapon Rules tables

INSERT INTO weapons_rules (weapon_id, rule_id)
VALUES
    (1, 1),
    (1, 2)
;