-- Active: 1710930161670@@127.0.0.1@5432@postgres

-- Fullfill Specific Tables --

-- Units table -- Unit_type could be: Infantry, Bikes - Jetbikes, Artillery, Jumps, Jet Packs, Beasts, Cavalry, Monsters, Vehicles, Flyers
INSERT INTO units (Unit_name, Faction_id, Unit_type, Nb_fig, M, BS, WS, S, T, W, A, I, Ld, OC, Sv, Invul_sv,
                   Keywords, Aptitude_name, Aptitude_desc, U_Pts)
VALUES
    ('CHAPLAIN GRIMALDUS', 1, 'Infantry', 1, '6"', '2+', '2+', 4, 4, 5, 4, 4, '6+', 1, '3+', '4++',
     'INFANTRY, CHARACTER, PRIEST, MASTER OF SANCTITY, CHAPLAIN, GRIMALDUS',
     ARRAY['Litanies of the Devout','Unmatched Zeal'],
     ARRAY['While Chaplain Grimaldus is leading a unit, each time a model in that unit makes a melee attack, you can re-roll the Hit roll.',
        'Friendly Black Templars units within 6" of Chaplain Grimaldus have the Zealot special rule.'],
     150)
;

-- Units Rules tables
INSERT INTO units_rules (unit_id, Rule_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Units Psy tables
INSERT INTO units_psy (unit_id, domains_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Units Rules tables
INSERT INTO units_weapons (unit_id, weapon_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Weapons table -- Weapon type could be: Melee, Assault - Heavy, Ordnance, Pistol, Psychic, Rapid Fire, Salvo, Bombs or Primary
INSERT INTO weapons (group_faction_id, Weapon_name, Weapon_type, Range, A, S, AP, D, W_Pts)
VALUES
    (1, 'Bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (1, 'Heavy bolt pistol', 'Pistol', '18"', '1', '4', '-1', '1', 5),
    (1, 'Special issue bolt pistol', 'Pistol', '12"', '1', '4', '0', '2', 0),
    (1, 'Absolvor bolt pistol', 'Pistol', '18"', '1', '5', '-1', '2', 5),
    (1, 'Assault boltgun', 'Pistol - Assault', '18"', '3', '5', '-1', '2', 10),
    (1, 'Boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Boltrifle', 'Assault - Heavy', '24"', '2', '4', '-1', '1', 5),
    (1, 'Twin boltrifle', 'Assault - Heavy', '24"', '2', '4', '-1', '1', 10),
    (1, 'Boltstorm', 'Pistol', '12"', '3', '4', '-1', '1', 5),
    (1, 'Instigator bolt carbine', 'Assault', '30"', '1', '4', '-2', '2', 10),
    (1, 'Occulus bolt carbine', 'Assault', '30"', '2', '4', '0', '2', 10),
    (1, 'Marksman bolt carbine', 'Heavy', '24"', '2', '4', '0', '2', 5),
    (1, 'Stalker pattern boltgun', 'Heavy', '30"', '2', '4', '-1', '1', 5),
    (1, 'Bolt sniper rifle', 'Heavy', '36"', '1', '5', '-2', '3', 10),
    (1, 'Ammunition Dragonfire Bolt', '=', '=', '=', '=', '=', '=', 0),
    (1, 'Ammunition Hellfire Round', '=', '=', '=', '-3', '-1', '=', 0),
    (1, 'Ammunition Kraken Bolt', '=', '+25%', '=', '=', '=', '=', 0),
    (1, 'Ammunition Vengeance Round', '=', '-25%', '=', '=', '-3', '=', 0),
    (1, 'Twin boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 5),
    (1, 'Hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 15),
    (1, 'Twin hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 20),
    (1, 'Heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 10),
    (1, 'Twin heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 15),
    (1, 'Storm bolter', 'Rapid Fire 2', '24"', '2', '4', '0', '1', 0),
    (1, 'Condemnor strake (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Condemnor strake (Crossbow)', 'Assault - Rapid Fire 1', '24"', '1', '5', '0', '1', 5),
    (1, 'Infernus heavy bolter (Heavy bolter)', 'Assault - Heavy', '36"', '3', '5', '-1', '2', 10),
    (1, 'Infernus heavy bolter (Heavy Flamer)', 'Assault - Heavy', 'Template', '1', '5', '-1', '1', 10),
    (1, 'Infernus heavy bolter (Hellfire shell)', 'Heavy', '24"', '1', '1', '0', 'D3', 10),
    (1, 'Hand flamer', 'Pistol', 'Template', '1', '3', '0', '1', 5),
    (1, 'Flamer', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (1, 'Combi-flamer (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-flamer (Flamer)', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (1, 'Hellfire Extremis (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Hellfire Extremis (Hellfire)', 'Assault', 'Template', '1', '4', '-1', '2', 10),
    (1, 'Heavy flamer', 'Assault', 'Template', '1', '5', '-1', '1', 10),
    (1, 'Twin heavy flamer', 'Assault', 'Template', '1', '5', '-1', '2', 15),
    (1, 'Pyroclast flame projector (Dispersed)', 'Assault', 'Template', '1', '6', '-1', '1', 10),
    (1, 'Pyroclast flame projector (Focused)', 'Assault', '6"', '1', '7', '-5', 'D6', 10),
    (1, 'Dreadfire heavy flamer (Separated)', 'Assault', 'Template', '2', '5', '-1', '1', 10),
    (1, 'Dreadfire heavy flamer (Combined)', 'Assault', 'Template', '1', '9', '-4', 'D3+3', 10),
    (1, 'Incendium cannon', 'Assault - Heavy', 'Template', '1', '4', '0', 'D3', 5),
    (1, 'Incendine combustor', 'Assault', 'Template', '1', '6', '-1', '1', 10),
    (1, 'Neo-volkite pistol', 'Pistol', '12"', '1', '5', '0', '2', 5),
    (1, 'Meltagun', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (1, 'Meltarifle', 'Heavy', '18"', '1', '9', '-4', 'D6', 15),
    (1, 'Combi-melta (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-melta (Meltagun)', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (1, 'Multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 20),
    (1, 'Twin multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 25),
    (1, 'Thermal spear', 'Assault', '24"', '2', '12', '-4', 'D6', 30),
    (1, 'Thermal cannon', 'Heavy', '24"', '2D3', '12', '-4', 'D6', 35),
    (1, 'Grav-pistol', 'Pistol', '12"', '1', '4', '-1', '1', 5),
    (1, 'Grav-gun', 'Salvo 2/3', '18"', '2', '5', '-1', '2', 10),
    (1, 'Combi-grav (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-grav (Grav-gun)', 'Salvo 2/3', '18"', '2', '5', '-1', '2', 10),
    (1, 'Grav-cannon', 'Salvo 3/5', '30"', '4', '5', '-1', '2', 15),
    (1, 'Plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (1, 'Plasma pistol (Supercharge)', 'Pistol', '12"', '1', '8', '-3', '2', 5),
    (1, 'Plasma gun (Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (1, 'Plasma gun (Supercharge)', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (1, 'Plasma cutter', 'Assault', '12"', '1', '7', '-2', '1', 10),
    (1, 'Plasma incinerator (Standard)', 'Assault - Heavy', '24"', '2', '7', '-2', '1', 5),
    (1, 'Plasma incinerator (Supercharge)', 'Assault - Heavy', '24"', '2', '8', '-3', '2', 10),
    (1, 'Plasma caliver (Standard)', 'Assault', '24"', '2', '7', '-2', '1', 5),
    (1, 'Plasma caliver (Supercharge)', 'Assault', '24"', '2', '8', '-3', '2', 5),
    (1, 'Combi-plasma (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-plasma (Plasma gun Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (1, 'Combi-plasma (Plasma gun Supercharge)', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (1, 'Plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (1, 'Plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 10),
    (1, 'Twin plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (1, 'Twin plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 15),
    (1, 'Heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (1, 'Heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 15),
    (1, 'Twin heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (1, 'Twin heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 20),
    (1, 'Frag cannon (Frag round)', 'Assault - Heavy - Rapid Fire D3', '18"', '2', '6', '0', '1', 10),
    (1, 'Frag cannon (Solid shell)', 'Assault - Heavy', '24"', '2', '7', '-3', 'D6', 10),
    (1, 'Ironhail heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '0', '1', 5),
    (1, 'Twin ironhail heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '0', '1', 10),
    (1, 'Questoris heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '-1', '1', 5),
    (1, 'Accelerator autocannon', 'Heavy', '48"', '3', '8', '-1', '2', 20),
    (1, 'Armiger autocannon', 'Heavy', '48"', '4', '9', '-1', '3', 25),
    (1, 'Icarus autocannon', 'Heavy', '48"', '3', '7', '-1', '2', 20),
    (1, 'Rapid fire battle cannon', 'Heavy - Rappid Fire D6+3', '72"', '3', '10', '-1', 'D3+3', 50),
    (1, 'Predator autocannon', 'Heavy - Rapid Fire 2', '48"', '4', '9', '-1', '3', 30),
    (1, 'Predator twin lascannon', 'Heavy', '48"', '1', '14', '-3', 'D6+1', 30),
    (1, 'Lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 20),
    (1, 'Twin lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 25),
    (1, 'Las-talon', 'Heavy', '36"', '2', '10', '-3', 'D6+1', 15),
    (1, 'Assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 15),
    (1, 'Twin assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 20),
    (1, 'Onslaught gatling cannon', 'Heavy', '24"', '8', '6', '0', '1', 15),
    (1, 'Avenger gatling cannon', 'Heavy', '36"', '18', '6', '-2', '2', 35),
    (1, 'Arc pistol', 'Pistol', '12"', '1', '6', '-1', '1', 10),
    (1, 'Arc rifle', 'Rapid fire 1', '30"', '1', '8', '-1', 'D3', 10),
    (1, 'Phosphor serpenta', 'Pistol', '18"', '1', '5', '-1', '2', 10),
    (1, 'Heavy phosphor blaster', 'Heavy', '36"', '3', '6', '-1', '2', 20),
    (1, 'Kastelan phosphor blaster', 'Heavy', '24"', '3', '6', '-1', '1', 15),
    (1, 'Twin kastelan phosphor blaster', 'Heavy', '24"', '3', '6', '-1', '1', 20),
    (1, 'Onager heavy phosphor blaster', 'Heavy', '36"', '4', '6', '-1', '2', 25),
    (1, 'Twin onager heavy phosphor blaster', 'Heavy', '36"', '4', '6', '-1', '2', 30),
    (1, 'Macrostubber', 'Pistol', '12"', '5', '4', '0', '1', 5),
    (1, 'Cognis heavy stubber', 'Rapid fire 3', '36"', '3', '4', '0', '1', 5),
    (1, 'Gamma pistol', 'Pistol', '24"', '1', '6', '-1', 'D3', 10),
    (1, 'Solar atomiser', 'Assault', '18"', 'D3', '14', '-4', '3', 25),
    (1, 'Volkite blaster', 'Heavy', '24"', '3', '5', '0', '2', 5),
    (1, 'Eradication ray (Dissipated)', 'Heavy', '24"', '1', '6', '-1', 'D3', 10),
    (1, 'Eradication ray (Focused)', 'Heavy', '12"', 'D3', '8', '-2', '2', 10),
    (1, 'Eradication beamer (Dissipated)', 'Heavy', '36"', '2', '9', '-2', '1', 15),
    (1, 'Eradication beamer (Focused)', 'Heavy', '18"', '3', '9', '-3', 'D6', 15),
    (1, 'Galvanic rifle', 'Assault', '30"', '2', '4', '0', '1', 0),
    (1, 'Radium pistol', 'Pistol', '12"', '1', '3', '0', '1', 0),
    (1, 'Radium carbine', 'Assault', '18"', '3', '3', '0', '1', 0),
    (1, 'Transuranic arquebus', 'Heavy', '36"', '1', '7', '-2', 'D3', 15),
    (1, 'Neutron laser', 'Heavy', '48"', '2', '16', '-4', '2', 35),
    (1, 'Missile launcher (Frag)', 'Heavy', '48"', '1', '4', '0', '1', 10),
    (1, 'Missile launcher (Krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (1, 'Icarus array', 'Heavy', '48"', '6', '8', '-1', '2', 15),
    (1, 'Typhoon missile launcher (Frag)', 'Heavy', '48"', '2', '4', '0', '1', 10),
    (1, 'Typhoon missile launcher (Krak)', 'Heavy', '48"', '2', '9', '-2', 'D6', 10),
    (1, 'Stormstrike missile launcher', 'Heavy', '48"', '1', '8', '-4', 'D6', 20),
    (1, 'Skyhammer missile launcher', 'Heavy', '60"', '3', '7', '-1', 'D3', 20),
    (1, 'Deathwind launcher', 'Heavy', '12"', '1', '12', '0', 'D6+1', 5),
    (1, 'Fragstorm grenade launcher', 'Heavy', '18"', 'D3', '4', '0', '1', 5),
    (1, 'Ironstorm missile pod', 'Heavy', '48"', '1', '5', '0', 'D3', 20),
    (1, 'Hellfyre missile rack', 'Heavy', '36"', '2', '10', '-2', '3', 25),
    (1, 'Daedalus missile launcher', 'Heavy', '48"', '1', '10', '-2', 'D6+1', 20),
    (1, 'Blackstar rocket launcher (Corvid warhead)', 'Heavy', '30"', 'D6', '6', '-2', 'D6', 10),
    (1, 'Blackstar rocket launcher (Dracos warhead)', 'Heavy', '30"', '1', '4', '-1', 'D3', 10),
    (1, 'Blackstar cluster launcher (Frag cluster)', 'Bomb', '-', '1', '4', '0', 'D3+1', 10),
    (1, 'Blackstar cluster launcher (Infernus cluster)', 'Bomb', '-', '1', '5', '-2', 'D3', 10),
    (1, 'Bellicatus missile array (Frag)', 'Heavy', '48"', '1', '4', '0', '1', 5),
    (1, 'Bellicatus missile array (Icarus)', 'Heavy', '48"', '1', '8', '-1', '2', 10),
    (1, 'Bellicatus missile array (Krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (1, 'Repulsor defensive array', 'Assault', '18"', '4', '5', '-1', '1', 20),
    (1, 'Icarus rocket pod', 'Heavy', '24"', '1', '8', '-1', '2', 10),
    (1, 'Exitus pistol', 'Pistol', '12"', '3', '5', '-2', '3', 10),
    (1, 'Exitus rifle', 'Heavy', '48"', '1', '7', '-3', 'D3+3', 20),
    (1, 'Animus speculum', 'Assault', '24"', '1 - 8', '5', '-2', 'D3', 20),
    (1, 'Executioner (Needle pistol)', 'Pistol', '12"', '4', '2', '0', '1', 10),
    (1, 'Executioner (Bolt pistol)', 'Pistol', '12"', '4', '4', '0', '1', 5),
    (1, 'Neural shredder', 'Pistol', 'Template', '1', '1', '-4', 'D3', 15),
    (2, 'Plague bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (2, 'Inferno bolt pistol', 'Pistol', '12"', '1', '4', '-1', '1', 0),
    (2, 'Cultist firearm', 'Pistol', '12"', '1', '3', '0', '1', 0),
    (2, 'Bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (2, 'Boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Plague boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Inferno boltgun', 'Rapid Fire 1', '24"', '2', '4', '-1', '1', 0),
    (2, 'Twin boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 5),
    (2, 'Hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 15),
    (2, 'Twin hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 20),
    (2, 'Heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 10),
    (2, 'Twin heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 15),
    (2, 'Combi-bolter', 'Rapid Fire 2', '24"', '2', '4', '0', '1', 0),
    (2, 'Inferno combi-bolter', 'Rapid Fire 2', '24"', '2', '4', '-1', '1', 0),
    (2, 'Warpflame pistol', 'Pistol', 'Template', '1', '3', '-1', '1', 0),
    (2, 'Flamer', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (2, 'Combi-flamer (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-flamer (Flamer)', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (2, 'Warpflamer', 'Assault', 'Template', '1', '4', '-1', '1', 10),
    (2, 'Plague belcher', 'Assault', 'Template', '1', '4', '0', '1', 0),
    (2, 'Plague spewer', 'Assault', 'Template', '1', '5', '-1', '1', 10),
    (2, 'Plaguespitter', 'Assault', 'Template', '1', '6', '-1', '1', 15),
    (2, 'Plaguespurt gauntlet', 'Pistol', 'Template', '1', '3', '0', '1', 0),
    (2, 'Baleflamer', 'Assault', 'Template', '2', '6', '-1', 'D3', 10),
    (2, 'Twin heavy flamer', 'Assault', 'Template', '1', '5', '-1', '2', 15),
    (2, 'Fire of Tzeentch (Blue fire)', 'Assault', '18"', '3', '9', '-3', '3', 15),
    (2, 'Fire of Tzeentch (Pink fire)', 'Assault', 'Template', '1', '5', '-1', '2', 10),
    (2, 'Flickering flames', 'Assault', 'Template', '1', '4', '-1', '2', 10),
    (2, 'Burning roar', 'Assault', 'Template', '1', '4', '0', '1', 5),
    (2, 'Meltagun', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (2, 'Combi-melta (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-melta (Meltagun)', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (2, 'Multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 20),
    (2, 'Twin multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 25),
    (2, 'Plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (2, 'Plasma pistol (Supercharge)', 'Pistol', '12"', '1', '8', '-3', '2', 5),
    (2, 'Infected plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (2, 'Infected plasma pistol (Supercharge)', 'Pistol', '12"', '1', '8', '-3', '2', 5),
    (2, 'Plasma gun (Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (2, 'Plasma gun (Supercharge)', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (2, 'Combi-plasma (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-plasma (Plasma gun Standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (2, 'Combi-plasma (Plasma gun Supercharge)', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (2, 'Plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (2, 'Plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 10),
    (2, 'Twin plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (2, 'Twin plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 15),
    (2, 'Heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (2, 'Heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 15),
    (2, 'Twin heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (2, 'Twin heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 20),
    (2, 'Heavy stubber', 'Rapid Fire 3', '36"', '4', '4', '0', '1', 5),
    (2, 'Reaper autocannon', 'Heavy', '36"', '4', '7', '-1', '1', 15),
    (2, 'Hades autocannon', 'Heavy', '36"', '6', '8', '-1', '2', 25),
    (2, 'Predator autocannon', 'Heavy - Rapid Fire 2', '48"', '4', '9', '-1', '3', 30),
    (2, 'Predator twin lascannon', 'Heavy', '48"', '1', '14', '-3', 'D6+1', 30),
    (2, 'Lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 20),
    (2, 'Twin lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 25),
    (2, 'Assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 15),
    (2, 'Twin assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 20),
    (2, 'Defiler cannon', 'Ordnance', '72"', '1', '10', '-3', 'D6+3', 30),
    (2, 'Harvester cannon (Solid shells)', 'Heavy', '48"', '3', '10', '-1', '3', 20),
    (2, 'Harvester cannon (Flakk shells)', 'Heavy', '48"', '3', '7', '-2', '3', 20),
    (2, 'Skull cannon', 'Heavy', '48"', '2', '9', '-1', 'D3+1', 25),
    (2, 'Bubotic defiler cannon', 'Ordnance', '72"', '1', '10', '-3', 'D6+3', 35),
    (2, 'Soulburner', 'Assault', '24"', '2', '5', '-2', '1', 20),
    (2, 'Fatecaster greatbow', 'Assault - Rapid Fire 1', '30"', '1', '5', '-1', '2', 20),
    (2, 'Coruscating pink flames', 'Assault', '18"', '2', '4', '-1', '1', 0),
    (2, 'Coruscating blue flames', 'Assault', '18"', '3', '3', '-1', '1', 0),
    (2, 'Coruscating yellow flames', 'Assault', '18"', '4', '2', '-1', '1', 0),
    (2, 'Phosphex bombs', 'Assault', '6"', '1', '8', '-4', 'D3', 0),
    (2, 'Blight grenades', 'Assault', '8"', '1', '4', '0', '1', 5),
    (2, 'Blight launcher', 'Assault', '24"', '2', '6', '-1', '2', 10),
    (2, 'Blightreaper cannon', 'Heavy', '36"', '4', '7', '-2', '1', 25),
    (2, 'Missile launcher (Frag)', 'Heavy', '48"', '1', '4', '0', '1', 10),
    (2, 'Missile launcher (Krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (2, 'Stormstrike missile launcher', 'Heavy', '48"', '1', '8', '-4', 'D6', 20),
    (2, 'Skyhammer missile launcher', 'Heavy', '60"', '3', '7', '-1', 'D3', 20),
    (3, 'Shuriken pistol', 'Pistol', '12"', '1', '4', '-1', '1', 0),
    (3, 'Shuriken catapult', 'Assault', '18"', '1', '4', '-1', '1', 0),
    (3, 'Twin shuriken catapult', 'Assault', '18"', '1', '4', '-1', '1', 5),
    (3, 'Avenger shuriken catapult', 'Assault', '18"', '3', '4', '-1', '1', 5),
    (3, 'Shuriken cannon', 'Heavy', '24"', '3', '6', '-1', '2', 5),
    (3, 'Twin shuriken cannon', 'Heavy', '24"', '3', '6', '-1', '2', 10),
    (3, 'Singing spear', 'Assault', '12"', '1', '9', '-2', '3', 15),
    (3, 'Dragon fusion gun', 'Assault', '12"', '1', '9', '-4', 'D6', 15),
    (3, 'Dragon fusion gun', 'Assault', '18"', '1', '12', '-4', 'D6', 25),
    (3, 'Bright lance', 'Heavy', '36"', '1', '12', '-3', 'D6+2', 15),
    (3, 'Ranger long rifle', 'Heavy', '36"', '1', '4', '-1', '2', 10),
    (3, 'Chainsabres', 'Pistol - Assault', '12"', '2', '4', '-1', '1', 5),
    (3, 'Reaper launcher (Starshot)', 'Heavy', '48"', '1', '8', '-2', '2', 10),
    (3, 'Reaper launcher (Starswarm)', 'Heavy', '48"', '2', '5', '-1', '1', 10),
    (3, 'Tempest launcher', 'Heavy', '36"', '2', '4', '-1', '2', 20),
    (3, 'Lasblaster', 'Assault', '24"', '4', '4', '-1', '1', 5),
    (3, 'Hawk’s talon', 'Assault', '24"', '4', '5', '-1', '1', 5),
    (3, 'Grenade pack', 'Assault', '6"', '2', '3', '0', '1', 5),
    (3, 'Death spinner', 'Assault', 'Template', '1', '4', '-1', '1', 5),
    (3, 'Star lance', 'Assault', '6"', '1', '9', '-3', '2', 10),
    (3, 'Laser lance', 'Assault', '6"', '1', '6', '-2', '2', 5),
    (3, 'Aeldari missile launcher (Starshot)', 'Heavy', '48"', '1', '10', '-2', 'D6', 15),
    (3, 'Aeldari missile launcher (Sunburst)', 'Heavy', '48"', '1', '4', '-1', '1', 10),
    (3, 'Starcannon', 'Heavy', '36"', '2', '8', '-3', '2', 15),
    (3, 'Twin starcannon', 'Heavy', '36"', '2', '8', '-3', '2', 20),
    (3, 'Pulse laser', 'Heavy', '48"', '3', '9', '-2', 'D6', 20),
    (3, 'Scatter laser', 'Heavy', '36"', '6', '5', '0', '1', 10),
    (3, 'Prism cannon (Dispersed pulse)', 'Heavy', '60"', '2', '6', '-1', 'D3+3', 20),
    (3, 'Prism cannon (Focused lances)', 'Heavy', '60"', '2', '12', '-3', 'D6+3', 20),
    (3, 'Prism cannon (Penetrating lances)', 'Heavy', '60"', '2', '18', '-5', '6', 20),
    (3, 'Doomweaver (Dispersed)', 'Heavy', '48"', '3', '7', '0', 'D6', 15),
    (3, 'Doomweaver (Focused)', 'Heavy', 'Template', '2', '7', '0', '2', 15),
    (3, 'Heavy D-scythe', 'Assault', '18"', '2', '20', '-4', 'D6', 25),
    (3, 'D-scythe', 'Assault', '12"', 'D3', '20', '-4', '1', 20),
    (3, 'Wraithcannon', 'Assault', '18"', '1', '14', '-4', 'D6', 25),
    (3, 'Aeldari flamer', 'Assault', 'Template', '1', '4', '0', '1', 5),
    (3, 'Suncannon', 'Heavy', '48"', '2', '8', '-3', 'D6+2', 30),
    (3, 'Heavy wraithcannon', 'Assault', '36"', 'D3', '20', '-4', '2D6', 35),
    (3, 'Splinter pistol', 'Pistol - Assault', '12"', '1', '2', '0', '1', 0),
    (3, 'Splinter pods', 'Assault', '18"', '2', '2', '0', '1', 0),
    (3, 'Splinter rifle', 'Assault', '24"', '2', '2', '0', '1', 0),
    (3, 'Splinter cannon', 'Salvo 4/6', '36"', '3', '3', '-1', '2', 10),
    (3, 'Dark lance', 'Heavy', '36"', '1', '12', '-3', 'D6+2', 15),
    (3, 'Shredder', 'Assault', '18"', '1', '6', '0', 'D3', 10),
    (3, 'Blast pistol', 'Pistol', '6"', '1', '8', '-3', 'D3', 5),
    (3, 'Blaster', 'Assault', '18"', '1', '8', '-4', 'D6+1', 10),
    (3, 'Heat lance', 'Assault', '18"', '1', '14', '-4', 'D6', 10),
    (3, 'Haywire blaster', 'Heavy', '24"', '2', '3', '-1', '3', 10),
    (3, 'Sharcarbine', 'Assault', '18"', '3', '2', '0', '1', 5),
    (3, 'Disintegrator cannon', 'Heavy', '36"', '3', '5', '-2', '2', 15),
    (3, 'Torment grenades launcher', 'Assault', '24"', '1', '1', '0', 'D3', 10),
    (4, 'Atomiser beam', 'Assault', '12"', '3', '6', '-2', '1', 15),
    (4, 'Doomsday cannon (Low power)', 'Heavy', '24"', '1', '8', '-3', 'D3+4', 20),
    (4, 'Doomsday cannon (High power)', 'Primary', '72"', '1', '15', '-4', 'D6+4', 25),
    (4, 'Enmitic annihilator', 'Rapid Fire 2', '18"', '2', '6', '-1', '1', 10),
    (4, 'Gauss blaster', 'Assault', '24"', '2', '5', '-1', '1', 5),
    (4, 'Gauss cannon', 'Heavy', '24"', '3', '5', '-2', '2', 15),
    (4, 'Gauss flayer', 'Rapid Fire 1', '24"', '1', '4', '0', '1', 0),
    (4, 'Gauss flayer array', 'Salvo 5/10 - Rapid Fire 5', '24"', '5', '4', '0', '1', 10),
    (4, 'Gauss flux arc', 'Heavy - Rapid Fire 3', '24"', '3', '6', '-1', '1', 15),
    (4, 'Gauss reaper', 'Assault', '12"', '2', '5', '-1', '1', 5),
    (4, 'Heavy death ray', 'Heavy', '24"', '1', '12', '-4', 'D6+1', 20),
    (4, 'Particle beamer', 'Assault', '18"', '2', '6', '0', 'D3', 10),
    (4, 'Particle caster', 'Pistol', '12"', '3', '5', '0', '1', 5),
    (4, 'Particle shredder', 'Heavy', '18"', '1', '7', '-1', '2', 10),
    (4, 'Particle whip', 'Ordnance', '24"', '1', '8', '-1', 'D6+3', 35),
    (4, 'Plasmic lance', 'Assault', '18"', '3', '7', '-3', '2', 10),
    (4, 'Relic gauss blaster', 'Rapid Fire 2', '24"', '2', '5', '-1', '2', 10),
    (4, 'Rod of covenant', 'Assault', '12"', '1', '5', '-2', '2', 10),
    (4, 'Scouring eye', 'Pistol - Assault', '6"', '2', '5', '-1', '1', 5),
    (4, 'Staff of light', 'Assault', '18"', '3', '5', '-2', '1', 10),
    (4, 'Synaptic disintegrator', 'Heavy', '36"', '1', '5', '-2', '2', 10),
    (4, 'Tachyon arrow', 'Assault', '72"', '1', '16', '-5', 'D6+2', 25),
    (4, 'Tesla arc', 'Assault 3D6', '3"', '0', '4', '0', '1', 0),
    (4, 'Tesla cannon', 'Heavy', '24"', '4', '6', '0', '1', 10),
    (4, 'Tesla carbine', 'Assault', '18"', '2', '5', '0', '1', 0),
    (4, 'Tesla destructor', 'Heavy', '36"', '6', '8', '0', '2', 15),
    (4, 'Transdimensional beamer', 'Assault', '12"', '1', '4', '-2', '3', 10),
    (4, 'Twin tesla carbine', 'Assault', '18"', '2', '5', '0', '1', 5),
    (4, 'Twin particle beamer', 'Assault', '18"', '2', '6', '0', 'D3', 15),
    (4, 'Twin tesla destructor', 'Heavy', '36"', '6', '8', '0', '2', 20),
    (5, 'Kombi-skorcha (Shoota)', 'Assault - Rapid Fire 1', '18"', '2', '4', '0', '1', 0),
    (5, 'Kombi-skorcha (Skorcha)', 'Assault', 'Template', '1', '4', '0', '1', 5),
    (5, 'Slugga', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (5, 'Twin slugga', 'Pistol', '12"', '1', '4', '0', '1', 5),
    (5, 'Twin dakkagun', 'Assault - Rapid Fire 2', '18"', '3', '5', '0', '1', 5),
    (5, 'Shoota', 'Assault - Rapid Fire 1', '18"', '2', '4', '0', '1', 0),
    (5, 'Big shoota', 'Assault - Rapid Fire 2', '36"', '3', '5', '0', '1', 5),
    (5, 'Rokkit launcha', 'Assault', '24"', '2', '9', '-2', '1', 5),
    (5, 'Burna', 'Assault', 'Template', '1', '4', '0', '1', 0),
    (5, 'Kustom mega-blasta (Short range)', 'Pistol', '12"', '3', '9', '-2', 'D6', 5),
    (5, 'Kustom mega-blasta (Medium range)', 'Assault', '24"', '3', '9', '-2', 'D3', 10),
    (5, 'Kustom mega-blasta (Long range)', 'Heavy', '36"', '3', '9', '-2', '1', 15),
    (5, 'Deffgun', 'Heavy - Rapid Fire 1', '48"', '2', '8', '-1', '2', 10),
    (1, 'Infernus', 'Assault', '18"', '2', '8', '-5', 'D6', 0),
    (1, 'The Spear of Telesto', 'Assault', '12"', '1', '7', '-5', 'D3+3', 0),
    (1, 'The Furnaces Heart', 'Assault', '18"', '1', '6', '-4', 'D6', 0),
    (1, 'The Ardent Blade', 'Assault', 'Template', '1', '6', '-2', '1', 0),
    (2, 'The Widowmakers', 'Assault', '12"', '3', '4', '-1', '2', 0),
    (2, 'The Lantern', 'Pistol - Assault', '18"', '1', '9', '-4', '.3', 0),
    (3, 'The Wailing Doom', 'Assault', '12"', '1', '16', '-4', 'D6+2', 0),
    (3, 'The Silent Death', 'Assault', '12"', '6', '6', '-2', '1', 0),
    (3, 'Voidbringer', 'Heavy', '48"', '1', '6', '-3', '3', 0),
    (3, 'The Parasite’s Kiss', 'Pistol', '12"', '1', '2', '-1', '2', 0),
    (1, 'Castigation', 'Psychic', '18"', '1', '8', '-2', '3', 0),
    (1, 'Cleanse (Witchfire)', 'Psychic', '24"', 'D6', '5', '-1', 'D3', 0),
    (1, 'Cleanse (Focused Witchfire)', 'Psychic', '24"', 'D6', '6', '-2', 'D3', 0),
    (1, 'Smite (Witchfire)', 'Psychic', '12"', '5', '5', '-2', '2', 0),
    (1, 'Smite (Focused Witchfire)', 'Psychic', '12"', '5', '6', '-2', '2', 0),
    (2, 'Infernal Gaze (Witchfire)', 'Psychic', '24"', 'D6', '5', '-1', 'D3', 0),
    (2, 'Infernal Gaze (Focused Witchfire)', 'Psychic', '24"', 'D6', '6', '-2', 'D3', 0),
    (2, 'Rotwind', 'Psychic', '18"', '1', '7', '-2', 'D6+3', 0),
    (2, 'Plague Wind (Witchfire)', 'Psychic', 'Template', '2', '4', '-1', 'D6', 0),
    (2, 'Plague Wind (Focused Witchfire)', 'Psychic', 'Template', '2', '6', '-2', 'D6+3', 0),
    (2, 'Psyfire serpenta', 'Psychic', '15"', 'D3', '8', '-4', '1', 0),
    (2, 'Gaze of Magnus', 'Psychic', '24"', '3D3', '9', '-2', '3', 0),
    (2, 'Tzeentch’s Firestorm', 'Psychic', '24"', '2', '5', '-1', 'D6+3', 0),
    (2, 'Psychic Stalk', 'Psychic', '18"', '1', '6', '-1', 'D6', 0),
    (2, 'Arcane Fire', 'Psychic', 'Template', '1', '6', '-2', '1', 0),
    (2, 'Astral Blast', 'Psychic', '18"', 'D3', '6', '-2', '1', 0),
    (2, 'Warpsmite', 'Psychic', '18"', '1', '4', '-1', '1', 0),
    (2, 'Mutating Orbs', 'Psychic', '18"', '1', '9', '0', 'D3+1', 0),
    (2, 'Infernal Gateway (Witchfire)', 'Psychic', '24"', 'D6+3', '9', '-2', 'D3', 0),
    (2, 'Infernal Gateway (Focused Witchfire)', 'Psychic', '24"', 'D3+1', '9', '-3', 'D3', 0),
    (2, 'Infernal Flames (Witchfire)', 'Psychic', 'Template', '1', '6', '-1', '1', 0),
    (2, 'Infernal Flames (Focused Witchfire)', 'Psychic', 'Template', 'D3', '6', '-1', 'D3+1', 0),
    (2, 'Infernal cannon', 'Psychic', '24"', '6', '5', '-1', '2', 0),
    (2, 'Arcane Fireball (Witchfire)', 'Psychic', '18"', '3', '5', '-1', 'D3', 0),
    (2, 'Arcane Fireball (Focused Witchfire)', 'Psychic', '18"', '3', '6', '-2', 'D3', 0),
    (2, 'Warp Gaze', 'Psychic', '48"', '1', '12', '-2', '3', 0),
    (2, 'Hellfire Breath', 'Psychic', 'Template', '1', '5', '-1', '1', 0),
    (2, 'Torrent of burning blood', 'Psychic', 'Template', '1', '5', '-1', '2', 0),
    (3, 'Swirling soul energy', 'Psychic', 'Template', '2', '7', '-1', '2', 0),
    (3, 'Storm of Whispers', 'Psychic', 'Template', '1', '2', '-2', '3', 0),
    (3, 'Eldritch Storm', 'Psychic', '24"', '1', '6', '-2', 'D6+2', 0),
    (3, 'Destructor', 'Psychic', 'Template', '1', '5', '-1', '1', 0),
    (1, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Combat knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Combat blade', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (1, 'Paired combat blade', 'Melee', 'Melee', 'User', 'User', '-1', '1', 10),
    (1, 'Astartes chainsword', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (1, 'Force axe', 'Melee', 'Melee', 'User', '+2', '-2', 'D3', 15),
    (1, 'Force maul', 'Melee', 'Melee', 'User', '+3', '-1', 'D3', 15),
    (1, 'Force sword', 'Melee', 'Melee', 'User', '+1', '-3', 'D3', 15),
    (1, 'Power axe', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (1, 'Power maul', 'Melee', 'Melee', 'User', '+3', '-1', '1', 10),
    (1, 'Power sword', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (1, 'Crozius Arcanum', 'Melee', 'Melee', 'User', '+2', '-1', '2', 10),
    (1, 'Relic blade', 'Melee','Melee', '+1', '+1', '-2', '2', 10),
    (1, 'Executioner relic blade', 'Melee','Melee', '+1', '+3', '-2', '2', 15),
    (1, 'Xenophase blade', 'Melee','Melee', '+1', '+1', '-3', '3', 20),
    (1, 'Life-draining touch', 'Melee', 'Melee', 'User', 'User', '-2', '2', 10),
    (1, 'Neuro gauntlet', 'Melee', 'Melee', '-1', '+1', '0', '2', 10),
    (1, 'Phase sword', 'Melee','Melee', 'User', '+1', '-4', '1', 15),
    (1, 'Poison Blades', 'Melee','Melee', 'User', '+1', '0', '2', 10),
    (1, 'Arc scourge', 'Melee','Melee', 'User', '+1', '-1', '1', 5),
    (1, 'Arc maul', 'Melee','Melee', 'User', '+3', '-2', '2', 15),
    (1, 'Taser goad', 'Melee','Melee', 'User', '+3', '0', '2', 10),
    (1, 'Mechadendrite hive', 'Melee','Melee', '2D6', 'User', '0', '1', 5),
    (1, 'Servo-arm', 'Melee', 'Melee', '1', 'x2', '-2', '3', 15),
    (1, 'Omnissian power axe', 'Melee', 'Melee', 'User', '+2', '-2', '2', 15),
    (1, 'Crawls omnissian axe', 'Melee', 'Melee', 'User', '+4', '-2', '2', 20),
    (1, 'Vigil Spear (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', 'D3', 10),
    (1, 'Vigil Spear (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (1, 'Power fist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 15),
    (1, 'Lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (1, 'Twin lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 15),
    (1, 'Chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Heavy thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-4', '3', 25),
    (1, 'Boltstorm', 'Melee', 'Melee', '-2', 'x2', '-2', '3', 20),
    (1, 'Kastelan fist', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (1, 'Invictor fist', 'Melee', 'Melee', '+1', 'x2', '-2', '3', 20),
    (1, 'Dreadnought combat weapon', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (1, 'Dreadnought chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '3', 25),
    (1, 'Dreadnought lightning claw', 'Melee', 'Melee', '+1', '+1', '-2', '3', 15),
    (1, 'Thuderstrike gauntlet (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '8', 25),
    (1, 'Thuderstrike gauntlet (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '3', 25),
    (1, 'Reaper chaincleaver (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 15),
    (1, 'Reaper chaincleaver (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '1', 15),
    (1, 'Reaper chainsword (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', '6', 20),
    (1, 'Reaper chainsword (Sweep)', 'Melee', 'Melee', 'x3', 'User', '-3', '2', 25),
    (2, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Combat knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Improvised weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Chakhal flails', 'Melee', 'Melee', 'User', '+1', '0', '1', 0),
    (2, 'Chakhal mauler', 'Melee', 'Melee', 'User', '+2', '-1', '2', 0),
    (2, 'Dishonoured chainblades', 'Melee', 'Melee', '+1', '+1', '0', '1', 0),
    (2, 'Skullsmasher', 'Melee', 'Melee', '+2', '+1', '-1', '2', 0),
    (2, 'Pink claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Blue claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Yellow claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Plague knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 5),
    (2, 'Astartes chainsword', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (2, 'Berzerker chainsword', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (2, 'Berzerker chainaxe', 'Melee', 'Melee', 'User', 'User', '-2', '2', 10),
    (2, 'Nostraman chainglaive', 'Melee', 'Melee', 'User', '+1', '0', '2', 0),
    (2, 'Hideous Mutation', 'Melee', 'Melee', 'User', 'User', '-1', '2', 5),
    (2, 'Force axe', 'Melee', 'Melee', 'User', '+2', '-2', 'D3', 15),
    (2, 'Force maul', 'Melee', 'Melee', 'User', '+3', '-1', 'D3', 15),
    (2, 'Force sword', 'Melee', 'Melee', 'User', '+1', '-3', 'D3', 15),
    (2, 'Prosperine khopesh', 'Melee', 'Melee', 'User', '+1', '-3', '1', 15),
    (2, 'Force stave', 'Melee', 'Melee', 'User', '+3', '-1', '3', 15),
    (2, 'Shaman stave', 'Melee', 'Melee', 'User', '+2', '-1', 'D3', 10),
    (2, 'Corrupted staff', 'Melee', 'Melee', 'User', '+2', '-1', 'D3', 15),
    (2, 'Power axe', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (2, 'Axe of dismemberment', 'Melee', 'Melee', 'User', '+3', '-2', '2', 15),
    (2, 'Power maul', 'Melee', 'Melee', 'User', '+3', '-1', '1', 10),
    (2, 'Power sword', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (2, 'Balesword', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Blade of blood', 'Melee', 'Melee', 'User', '+1', '-2', '3', 10),
    (2, 'Attendant hellblades', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Hellbalde', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Divining spear', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (2, 'Exalted weapon', 'Melee', 'Melee', '+2', '+1', '-2', '2', 20),
    (2, 'Daemon blade', 'Melee', 'Melee', '+1', '+3', '-3', 'D3', 25),
    (2, 'Bubotic weapon', 'Melee', 'Melee', 'User', '+1', '-2', '1', 15),
    (2, 'Bubotic axe & Mace of Contagion', 'Melee', 'Melee', '+1', '+1', '-2', '2', 20),
    (2, 'Heavy plague weapon', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 25),
    (2, 'Cursed plague bell', 'Melee', 'Melee', '+1', 'User', '0', '2', 5),
    (2, 'Manreaper (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 10),
    (2, 'Manreaper (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (2, 'Plagueblade (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 10),
    (2, 'Plagueblade (Sweep)', 'Melee', 'Melee', 'x2', 'User', '0', '1', 10),
    (2, 'Plague probe', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (2, 'Greater plague probe', 'Melee', 'Melee', 'User', 'User', '-2', '1', 5),
    (2, 'Bile maw', 'Melee', 'Melee', 'User', '+2', '-1', '1', 5),
    (2, 'Great axe of Khorne (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', 'D6+2', 30),
    (2, 'Great axe of Khorne (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '2', 25),
    (2, 'Tzaangor blades', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Tzaangor heavy blades', 'Melee', 'Melee', '-1', '+2', '-1', '1', 5),
    (2, 'Flamer mouths', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Lamprey bites', 'Melee', 'Melee', 'User', 'User', '-2', '2', 5),
    (2, 'Juggernaut bladed horn', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Soul-rending fangs', 'Melee', 'Melee', 'User', 'User', '-1', '2', 5),
    (2, 'Gore-denched fangs', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Biting maw', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (2, 'Power fist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 15),
    (2, 'Bubotic power fist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Twin lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 15),
    (2, 'Warp claws', 'Melee', 'Melee', '+1', '+1', '-2', '1', 10),
    (2, 'Warpclaw', 'Melee', 'Melee', '+1', 'User', '-1', '2', 0),
    (2, 'Warpsword', 'Melee', 'Melee', 'User', 'User', '-2', 'D6', 5),
    (2, 'Daemons claw', 'Melee', 'Melee', 'User', 'user', '0', '1', 0),
    (2, 'Mutating warpblade (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 25),
    (2, 'Mutating warpblade (Sweep)', 'Melee', 'Melee', 'x2', 'User', '0', '1', 25),
    (2, 'Chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Heavy thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-4', '3', 25),
    (2, 'Dreadnought combat weapon', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (2, 'Dreadnought lightning claw', 'Melee', 'Melee', '+1', '+1', '-2', '3', 15),
    (2, 'Dreadnought chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '3', 25),
    (2, 'Helbrute fist', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (2, 'Defiler claw', 'Melee', 'Melee', 'User', 'x2', '-2', 'D3+3', 25),
    (2, 'Defiler scourge', 'Melee', 'Melee', '+2', '+4', '-1', '2', 20),
    (2, 'Bubotic defiler scourge', 'Melee', 'Melee', '+2', '+4', '-1', '2', 25),
    (3, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (3, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (3, 'Witchblade', 'Melee', 'Melee', 'User', '+1', '-2', '2', 15),
    (3, 'Singing spear (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 15),
    (3, 'Singing spear (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 15),
    (3, 'Witchstaff', 'Melee', 'Melee', 'User', '+2', '0', 'D3', 10),
    (3, 'Aeldari power sword', 'Melee', 'Melee', 'User', '+1', '-2', '1', 10),
    (3, 'Star glaive (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '2', 15),
    (3, 'Star glaive (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 15),
    (3, 'Banshee blade', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (3, 'Mirrorswords', 'Melee', 'Melee', '+1', '+1', '-3', '1', 10),
    (3, 'Executioner', 'Melee', 'Melee', 'User', '+2', '-2', '2', 10),
    (3, 'Diresword', 'Melee', 'Melee', 'User', '+1', '-2', '1', 10),
    (3, 'Scorpion chainsword', 'Melee', 'Melee', '+1', '+1', '-1', '2', 10),
    (3, 'Chainsabres', 'Melee', 'Melee', 'User', '+1', '0', '1', 5),
    (3, 'Powerblades', 'Melee', 'Melee', '+1', '+1', '-2', '1', 10),
    (3, 'Star lance', 'Melee', 'Melee', '+1', 'User', '-3', '2', 5),
    (3, 'Laser lance', 'Melee', 'Melee', 'User', 'User', '-2', '2', 5),
    (3, 'Ghostaxe', 'Melee', 'Melee', 'User', '+2', '-2', '2', 10),
    (3, 'Ghostswords', 'Melee', 'Melee', '+1', '+1', '-2', '1', 10),
    (3, 'Wraithbone fists', 'Melee', 'Melee', 'User', 'User', '-2', '2', 10),
    (3, 'Ghostglaive (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', 'D6+1', 15),
    (3, 'Ghostglaive (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '2', 10),
    (3, 'Titanic ghostglaive (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '6', 20),
    (3, 'Titanic ghostglaive (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '2', 15),
    (3, 'Demiklaives (Single-blade)', 'Melee', 'Melee', 'User', 'x2', '-2', '2', 15),
    (3, 'Demiklaives (Dual-blade)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (3, 'Klaive', 'Melee', 'Melee', 'User', '+1', '-2', '2', 15),
    (3, 'Drukhari power blade', 'Melee', 'Melee', '+1', 'User', '-2', '1', 10),
    (3, 'Agoniser', 'Melee', 'Melee', '+1', 'User', '-1', '1', 5),
    (3, 'Hekatarii blades', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (3, 'Razorflail', 'Melee', 'Melee', 'User', 'User', '-2', '1', 10),
    (3, 'Mindphase Gauntlet', 'Melee', 'Melee', 'User', 'User', '-1', '1', 10),
    (3, 'Shardnet & Implaler', 'Melee', 'Melee', 'User', 'User', '-1', '2', 10),
    (3, 'Implaler', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (3, 'Hellglaive', 'Melee', 'Melee', 'User', '+1', '-1', '2', 10),
    (3, 'Stunclaw', 'Melee', 'Melee', 'User', '+1', '0', '1', 0),
    (3, 'Bladevanes', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Automaton claws', 'Melee', 'Melee', 'User', '+2', '-2', '2', 15),
    (4, 'Empathic Obliterator', 'Melee', 'Melee', 'User', '+2', '-1', 'D3', 0),
    (4, 'Feeder mandibles', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Flensing claw', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (4, 'Hyperphase glaive', 'Melee', 'Melee', 'User', '+2', '-2', 'D3', 10),
    (4, 'Hyperphase harvester', 'Melee', 'Melee', 'User', '+4', '-3', '3', 20),
    (4, 'Hyperphase reap-blade', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (4, 'Hyperphase sword', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (4, 'Hyperphase threshers', 'Melee', 'Melee', '+1', 'User', '-1', '1', 10),
    (4, 'Plasmic lance', 'Melee', 'Melee', 'User', '+3', '-3', '2', 10),
    (4, 'Portal of exile', 'Melee', 'Melee', 'User', 'User', '-2', '3', 15),
    (4, 'Reanimator’s claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (4, 'Rod of covenant', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (4, 'Staff of light', 'Melee', 'Melee', 'User', '+1', '-2', '1', 10),
    (4, 'Stalker’s forelimbs (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 10),
    (4, 'Stalker’s forelimbs (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (4, 'Vicious claws', 'Melee', 'Melee', 'User', '+4', '-1', '2', 10),
    (4, 'Voidblade', 'Melee', 'Melee', 'User', 'x2', '-3', '2', 15),
    (4, 'Whip coils', 'Melee', 'Melee', 'x2', 'User', '0', '1', 5),
    (5, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (5, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (5, 'Power Klaw', 'Melee', 'Melee', 'User', 'x2', '-2', '2', 15),
    (5, 'Attack squig', 'Melee', 'Melee', 'User', 'User', '0', '1', 15),
    (5, 'Choppa', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (5, 'Big choppa', 'Melee', 'Melee', '-1', '+3', '-1', '2', 5),
    (5, 'Cuttin’flames', 'Melee', 'Melee', 'User', 'User', '-2', '1', 5),
    (5, 'Wreckin’ball', 'Melee', 'Melee', '+D3', '+5', '-2', 'D3+3', 15),
    (1, 'Black Sword (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 0),
    (1, 'Black Sword (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '1', 0),
    (1, 'The Spear of Telesto (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', 'D3+1', 0),
    (1, 'The Spear of Telesto (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-3', 'D3', 0),
    (1, 'Moonsilver', 'Melee', 'Melee', 'User', 'User', '-3', '2', 0),
    (1, 'Dawnbringer', 'Melee', 'Melee', 'User', '+3', '-5', 'D3+3', 0),
    (1, 'The Ardent Blade', 'Melee', 'Melee', '+1', '+1', '-3', '1', 0),
    (2, 'Mercy & Forgiveness', 'Melee', 'Melee', 'User', '+1', '-4', 'D6', 0),
    (2, 'Claws of the Black Hunt', 'Melee', 'Melee', '+3', '+2', '-3', 'D3+2', 35),
    (2, 'Silence (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '4', 0),
    (2, 'Silence (Sweep)', 'Melee', 'Melee', 'x3', 'User', '-1', '1', 0),
    (2, 'The Blade of Ahn-Nunurta (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 0),
    (2, 'The Blade of Ahn-Nunurta (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 0),
    (2, 'Black Staff of Ahriman', 'Melee', 'Melee', '+1', '+3', '-1', '3', 0),
    (2, 'Seer’s Bane', 'Melee', 'Melee', 'User', '+1', '-3', 'D3', 0),
    (2, 'Gorechild', 'Melee', 'Melee', 'User', '+2', '-2', '3', 0),
    (2, 'Staff of Tommorrow', 'Melee', 'Melee', 'User', '+2', '-2', '2D3', 0),
    (2, 'The Trickster Staff', 'Melee', 'Melee', 'User', '+1', '-1', 'D3', 0),
    (2, 'Sharp quills', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'The Slayer Sword', 'Melee', 'Melee', 'User', '+2', '-2', '3', 0),
    (3, 'The Wailing Doom (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', 'D6+2', 0),
    (3, 'The Wailing Doom (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '2', 0),
    (3, 'Vilith-zhar, the Sword of Souls (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', 'D6+1', 0),
    (3, 'Vilith-zhar, the Sword of Souls (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-4', '1', 0),
    (3, 'Asu-var, the Sword of Silent Screams', 'Melee', 'Melee', 'User', 'User', '-4', '2', 0),
    (3, 'Kha-vir, the Sword of Sorrows', 'Melee', 'Melee', 'User', 'User', '-3', '2', 0),
    (3, 'The Staff of Ulthamar', 'Melee', 'Melee', 'User', '+2', '-1', '2', 0),
    (3, 'The Blade of Destruction (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '2', 0),
    (3, 'The Blade of Destruction (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-3', '1', 0),
    (3, 'The Triptych Whip', 'Melee', 'Melee', '+3', 'User', '-2', '1', 0),
    (3, 'The Executioner’s (Single-blade)', 'Melee', 'Melee', '+1', '+2', '-2', '3', 0),
    (3, 'The Executioner’s (Dual-blade)', 'Melee', 'Melee', '+3', '+1', '-2', '2', 0),
    (3, 'Lelith’s blades', 'Melee', 'Melee', 'User', 'User', '-2', '1', 0)
;

-- Weapon Rules tables

INSERT INTO weapons_rules (weapon_id, rule_id)
VALUES
    (1, 1),
    (1, 2)
;