-- Active: 1710930161670@@127.0.0.1@5432@postgres

-- Fullfill Specific Tables --

-- Units table -- Unit_type could be: Infantry, Bikes - Jetbikes, Artillery, Jumps, Jet Packs, Beasts, Cavalry, Monsters, Vehicles, Flyers
INSERT INTO units (Unit_name, Faction_id, Unit_type, Nb_fig, M, BS, WS, S, T, W, A, I, Ld, OC, Sv, Invul_sv,
                   Keywords, Aptitude_name, Aptitude_desc, U_Pts)
VALUES
    ('CHAPLAIN GRIMALDUS', 1, 'Infantry', 1, '6"', '2+', '2+', 4, 4, 5, 4, 4, '6+', 1, '3+', '4++',
     'INFANTRY, CHARACTER, PRIEST, MASTER OF SANCTITY, CHAPLAIN, GRIMALDUS',
     ARRAY['Litanies of the Devout','Unmatched Zeal'],
     ARRAY['While Chaplain Grimaldus is leading a unit, each time a model in that unit makes a melee attack, you can re-roll the Hit roll.',
        'Friendly Black Templars units within 6" of Chaplain Grimaldus have the Zealot special rule.'],
     150)
;

-- Units Rules tables
INSERT INTO units_rules (unit_id, Rule_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Units Psy tables
INSERT INTO units_psy (unit_id, domains_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Units Rules tables
INSERT INTO units_weapons (unit_id, weapon_id)
VALUES
    (1, 1),
    (1, 2)
;

-- Weapons table -- Weapon type could be: Melee, Assault, Heavy, Ordnance, Pistol, Psychic, Rapid Fire, Salvo, Bombs or Primary
INSERT INTO weapons (group_faction_id, Weapon_name, Weapon_type, Range, A, S, AP D, W_Pts)
VALUES
    (1, 'Bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (2, 'Bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (2, 'Plague bolt pistol', 'Pistol', '12"', '1', '4', '0', '1', 0),
    (2, 'Inferno bolt pistol', 'Pistol', '12"', '1', '4', '-1', '1', 0),
    (2, 'Cultist firearm', 'Pistol', '12"', '1', '3', '0', '1', 0),
    (1, 'Heavy bolt pistol', 'Pistol', '18"', '1', '4', '-1', '1', 5),
    (1, 'Special issue bolt pistol', 'Pistol', '12"', '1', '4', '0', '2', 0),
    (1, 'Absolvor bolt pistol', 'Pistol', '18"', '1', '5', '-1', '2', 5),
    (1, 'Assault boltgun', 'Pistol, Assault', '18"', '3', '5', '-1', '2', 10),
    (1, 'Boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Plague boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Inferno boltgun', 'Rapid Fire 1', '24"', '2', '4', '-1', '1', 0),
    (1, 'Boltrifle', 'Assault, Heavy', '24"', '2', '4', '-1', '1', 5),
    (1, 'Twin boltrifle', 'Assault, Heavy', '24"', '2', '4', '-1', '1', 10),
    (1, 'Boltstorm', 'Pistol', '12"', '3', '4', '-1', '1', 5),
    (1, 'Instigator bolt carbine', 'Assault', '30"', '1', '4', '-2', '2', 10),
    (1, 'Occulus bolt carbine', 'Assault', '30"', '2', '4', '0', '2', 10),
    (1, 'Marksman bolt carbine', 'Heavy', '24"', '2', '4', '0', '2', 5),
    (1, 'Stalker pattern boltgun', 'Heavy', '30"', '2', '4', '-1', '1', 5),
    (1, 'Bolt sniper rifle', 'Heavy', '36"', '1', '5', '-2', '3', 10),
    (1, 'Ammunition Dragonfire Bolt', '=', '=', '=', '=', '=', '=', 0),
    (1, 'Ammunition Hellfire Round', '=', '=', '=', '-3', '-1', '=', 0),
    (1, 'Ammunition Kraken Bolt', '=', '+25%', '=', '=', '=', '=', 0),
    (1, 'Ammunition Vengeance Round', '=', '-25%', '=', '=', '-3', '=', 0),
    (1, 'Twin boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 5),
    (2, 'Twin boltgun', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 5),
    (1, 'Hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 15),
    (2, 'Hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 15),
    (1, 'Twin hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 20),
    (2, 'Twin hurricane boltgun', 'Rapid Fire 6', '24"', '6', '4', '0', '1', 20),
    (1, 'Heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 10),
    (2, 'Heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 10),
    (1, 'Twin heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 15),
    (2, 'Twin heavy bolter', 'Heavy', '36"', '3', '5', '-1', '2', 15),
    (1, 'Storm bolter', 'Rapid Fire 2', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-bolter', 'Rapid Fire 2', '24"', '2', '4', '0', '1', 0),
    (2, 'Inferno combi-bolter', 'Rapid Fire 2', '24"', '2', '4', '-1', '1', 0),
    (1, 'Condemnor strake (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Condemnor strake (Crossbow)', 'Assault, Rapid Fire 1', '24"', '1', '5', '0', '1', 5),
    (1, 'Infernus heavy bolter (Heavy bolter)', 'Heavy, Assault', '36"', '3', '5', '-1', '2', 10),
    (1, 'Infernus heavy bolter (Heavy Flamer)', 'Heavy, Assault', 'Template', '1', '5', '-1', '1', 10),
    (1, 'Infernus heavy bolter (Hellfire shell)', 'Heavy', '24"', '1', '1', '0', 'D3', 10),
    (1, 'Hand flamer', 'Pistol', 'Template', '1', '3', '0', '1', 5),
    (2, 'Warpflame pistol', 'Pistol', 'Template', '1', '3', '-1', '1', 0),
    (1, 'Flamer', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (2, 'Flamer', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (1, 'Combi-flamer (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-flamer (Flamer)', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (2, 'Combi-flamer (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-flamer (Flamer)', 'Assault', 'Template', '1', '4', '0', '1', 10),
    (2, 'Warpflamer', 'Assault', 'Template', '1', '4', '-1', '1', 10),
    (2, 'Plague belcher', 'Assault', 'Template', '1', '4', '0', '1', 0),
    (2, 'Plague spewer', 'Assault', 'Template', '1', '5', '-1', '1', 10),
    (2, 'Plaguespitter', 'Assault', 'Template', '1', '6', '-1', '1', 15),
    (2, 'Plaguespurt gauntlet', 'Pistol', 'Template', '1', '3', '0', '1', 0),
    (1, 'Hellfire Extremis (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Hellfire Extremis (Hellfire)', 'Assault', 'Template', '1', '4', '-1', '2', 10),
    (1, 'Heavy flamer', 'Assault', 'Template', '1', '5', '-1', '1', 10),
    (2, 'Baleflamer', 'Assault', 'Template', '2', '6', '-1', 'D3', 10),
    (1, 'Twin heavy flamer', 'Assault', 'Template', '1', '5', '-1', '2', 15),
    (2, 'Twin heavy flamer', 'Assault', 'Template', '1', '5', '-1', '2', 15),
    (1, 'Pyroclast flame projector (dispersed)', 'Assault', 'Template', '1', '6', '-1', '1', 10),
    (1, 'Pyroclast flame projector (focused)', 'Assault', '6"', '1', '7', '-5', 'D6', 10),
    (1, 'Dreadfire heavy flamer (separated)', 'Assault', 'Template', '2', '5', '-1', '1', 10),
    (1, 'Dreadfire heavy flamer (combined)', 'Assault', 'Template', '1', '9', '-4', 'D3+3', 10),
    (1, 'Incendium cannon', 'Assault, Heavy', 'Template', '1', '4', '0', 'D3', 5),
    (1, 'Incendine combustor', 'Assault', 'Template', '1', '6', '-1', '1', 10),
    (2, 'Fire of Tzeentch (blue fire)', 'Assault', '18"', '3', '9', '-3', '3', 15),
    (2, 'Fire of Tzeentch (pink fire)', 'Assault', 'Template', '1', '5', '-1', '2', 10),
    (2, 'Flickering flames', 'Assault', 'Template', '1', '4', '-1', '2', 10),
    (2, 'Burning roar', 'Assault', 'Template', '1', '4', '0', '1', 5),
    (1, 'Neo-volkite pistol', 'Pistol', '12"', '1', '5', '0', '2', 5),
    (1, 'Meltagun', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (2, 'Meltagun', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (1, 'Meltarifle', 'Heavy', '18"', '1', '9', '-4', 'D6', 15),
    (1, 'Combi-melta (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-melta (Meltagun)', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (2, 'Combi-melta (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-melta (Meltagun)', 'Assault', '12"', '1', '9', '-4', 'D6', 10),
    (1, 'Multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 20),
    (2, 'Multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 20),
    (1, 'Twin multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 25),
    (2, 'Twin multi-melta', 'Heavy', '18"', '2', '9', '-4', 'D6', 25),
    (1, 'Thermal spear', 'Assault', '24"', '2', '12', '-4', 'D6', 30),
    (1, 'Thermal cannon', 'Heavy', '24"', '2D3', '12', '-4', 'D6', 35),
    (1, 'Grav-pistol', 'Pistol', '12"', '1', '4', '-1', '1', 5),
    (1, 'Grav-gun', 'Salvo 2/3', '18"', '2', '5', '-1', '2', 10),
    (1, 'Combi-grav (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-grav (Grav-gun)', 'Salvo 2/3', '18"', '2', '5', '-1', '2', 10),
    (1, 'Grav-cannon', 'Salvo 3/5', '30"', '4', '5', '-1', '2', 15),
    (1, 'Plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (1, 'Plasma pistol (Supercharge)', 'Pistol', '12"', '1', '8', '-3', '2', 5),
    (2, 'Plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (2, 'Plasma pistol (Supercharge)', 'Pistol', '12"', '1', '8', '-3', '2', 5),
    (2, 'Infected plasma pistol (Standard)', 'Pistol', '12"', '1', '7', '-2', '1', 5),
    (2, 'Infected plasma pistol (Supercharge)', 'Pistol', '12"', '1', '8', '-3', '2', 5),
    (1, 'Plasma gun standard', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (1, 'Plasma gun supercharge', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (2, 'Plasma gun standard', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (2, 'Plasma gun supercharge', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (1, 'Plasma cutter standard', 'Assault', '12"', '1', '7', '-2', '1', 10),
    (1, 'Plasma incinerator standard', 'Assault, Heavy', '24"', '2', '7', '-2', '1', 5),
    (1, 'Plasma incinerator supercharge', 'Assault, Heavy', '24"', '2', '8', '-3', '2', 10),
    (1, 'Plasma caliver standard', 'Assault', '24"', '2', '7', '-2', '1', 5),
    (1, 'Plasma caliver supercharge', 'Assault', '24"', '2', '8', '-3', '2', 5),
    (1, 'Combi-plasma (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (1, 'Combi-plasma (Plasma gun standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (1, 'Combi-plasma (Plasma gun supercharge)', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (2, 'Combi-plasma (Boltgun)', 'Rapid Fire 1', '24"', '2', '4', '0', '1', 0),
    (2, 'Combi-plasma (Plasma gun standard)', 'Rapid Fire 1', '24"', '1', '7', '-2', '1', 5),
    (2, 'Combi-plasma (Plasma gun supercharge)', 'Rapid Fire 1', '24"', '1', '8', '-3', '2', 10),
    (1, 'Plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (1, 'Plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 10),
    (2, 'Plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (2, 'Plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 10),
    (1, 'Twin plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (1, 'Twin plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 15),
    (2, 'Twin plasma cannon (Standard)', 'Heavy', '36"', '1', '7', '-2', '1', 10),
    (2, 'Twin plasma cannon (Supercharge)', 'Heavy', '36"', '1', '8', '-3', '2', 15),
    (1, 'Heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (1, 'Heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 15),
    (2, 'Heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (2, 'Heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 15),
    (1, 'Twin heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (1, 'Twin heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 20),
    (2, 'Twin heavy plasma cannon (Standard)', 'Heavy', '36"', 'D3', '7', '-2', '1', 15),
    (2, 'Twin heavy plasma cannon (Supercharge)', 'Heavy', '36"', 'D3', '8', '-3', '2', 20),
    (1, 'Frag cannon (Frag round)', 'Heavy, Assault, Rapid Fire D3', '18"', '2', '6', '0', '1', 10),
    (1, 'Frag cannon (Solid shell)', 'Heavy, Assault', '24"', '2', '7', '-3', 'D6', 10),
    (2, 'Heavy stubber', 'Rapid Fire 3', '36"', '4', '4', '0', '1', 5),
    (1, 'Ironhail heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '0', '1', 5),
    (1, 'Twin ironhail heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '0', '1', 10),
    (1, 'Questoris heavy stubber', 'Rapid Fire 3', '36"', '3', '4', '-1', '1', 5),
    (1, 'Accelerator autocannon', 'Heavy', '48"', '3', '8', '-1', '2', 20),
    (1, 'Armiger autocannon', 'Heavy', '48"', '4', '9', '-1', '3', 25),
    (1, 'Icarus autocannon', 'Heavy', '48"', '3', '7', '-1', '2', 20),
    (2, 'Reaper autocannon', 'Heavy', '36"', '4', '7', '-1', '1', 15),
    (2, 'Hades autocannon', 'Heavy', '36"', '6', '8', '-1', '2', 25),
    (1, 'Rapid fire battle cannon', 'Heavy, Rappid Fire D6+3', '72"', '3', '10', '-1', 'D3+3', 50),
    (1, 'Predator autocannon', 'Heavy, Rapid Fire 2', '48"', '4', '9', '-1', '3', 30),
    (2, 'Predator autocannon', 'Heavy, Rapid Fire 2', '48"', '4', '9', '-1', '3', 30),
    (1, 'Predator twin lascannon', 'Heavy', '48"', '1', '14', '-3', 'D6+1', 30),
    (2, 'Predator twin lascannon', 'Heavy', '48"', '1', '14', '-3', 'D6+1', 30),
    (1, 'Lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 20),
    (2, 'Lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 20),
    (1, 'Twin lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 25),
    (2, 'Twin lascannon', 'Heavy', '48"', '1', '12', '-3', 'D6+1', 25),
    (1, 'Las-talon', 'Heavy', '36"', '2', '10', '-3', 'D6+1', 15),
    (1, 'Assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 15),
    (2, 'Assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 15),
    (1, 'Twin assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 20),
    (2, 'Twin assault cannon', 'Heavy', '24"', '6', '6', '0', '1', 20),
    (2, 'Defiler cannon', 'Ordnance', '72"', '1', '10', '-3', 'D6+3', 30),
    (2, 'Harvester cannon (solid shells)', 'Heavy', '48"', '3', '10', '-1', '3', 20),
    (2, 'Harvester cannon (flakk shells)', 'Heavy', '48"', '3', '7', '-2', '3', 20),
    (2, 'Skull cannon', 'Heavy', '48"', '2', '9', '-1', 'D3+1', 25),
    (2, 'Bubotic defiler cannon', 'Ordnance', '72"', '1', '10', '-3', 'D6+3', 35),
    (1, 'Onslaught gatling cannon', 'Heavy', '24"', '8', '6', '0', '1', 15),
    (1, 'Avenger gatling cannon', 'Heavy', '36"', '18', '6', '-2', '2', 35),
    (1, 'Arc pistol', 'Pistol', '12"', '1', '6', '-1', '1', 10),
    (1, 'Arc rifle', 'Rapid fire 1', '30"', '1', '8', '-1', 'D3', 10),
    (1, 'Phosphor serpenta', 'Pistol', '18"', '1', '5', '-1', '2', 10),
    (1, 'Heavy phosphor blaster', 'Heavy', '36"', '3', '6', '-1', '2', 20),
    (1, 'Kastelan phosphor blaster', 'Heavy', '24"', '3', '6', '-1', '1', 15),
    (1, 'Twin kastelan phosphor blaster', 'Heavy', '24"', '3', '6', '-1', '1', 20),
    (1, 'Onager heavy phosphor blaster', 'Heavy', '36"', '4', '6', '-1', '2', 25),
    (1, 'Twin onager heavy phosphor blaster', 'Heavy', '36"', '4', '6', '-1', '2', 30),
    (1, 'Macrostubber', 'Pistol', '12"', '5', '4', '0', '1', 5),
    (1, 'Cognis heavy stubber', 'Rapid fire 3', '36"', '3', '4', '0', '1', 5),
    (1, 'Gamma pistol', 'Pistol', '24"', '1', '6', '-1', 'D3', 10),
    (1, 'Solar atomiser', 'Assault', '18"', 'D3', '14', '-4', '3', 25),
    (1, 'Volkite blaster', 'Heavy', '24"', '3', '5', '0', '2', 5),
    (1, 'Eradication ray (dissipated)', 'Heavy', '24"', '1', '6', '-1', 'D3', 10),
    (1, 'Eradication ray (focused)', 'Heavy', '12"', 'D3', '8', '-2', '2', 10),
    (1, 'Eradication beamer (dissipated)', 'Heavy', '36"', '2', '9', '-2', '1', 15),
    (1, 'Eradication beamer (focused)', 'Heavy', '18"', '3', '9', '-3', 'D6', 15),
    (1, 'Galvanic rifle', 'Assault', '30"', '2', '4', '0', '1', 0),
    (1, 'Radium pistol', 'Pistol', '12"', '1', '3', '0', '1', 0),
    (1, 'Radium carbine', 'Assault', '18"', '3', '3', '0', '1', 0),
    (1, 'Transuranic arquebus', 'Heavy', '36"', '1', '7', '-2', 'D3', 15),
    (1, 'Neutron laser', 'Heavy', '48"', '2', '16', '-4', '2', 35),
    (2, 'Soulburner', 'Assault', '24"', '2', '5', '-2', '1', 20),
    (2, 'Fatecaster greatbow', 'Assault, Rapid Fire 1', '30"', '1', '5', '-1', '2', 20),
    (2, 'Coruscating pink flames', 'Assault', '18"', '2', '4', '-1', '1', 0),
    (2, 'Coruscating blue flames', 'Assault', '18"', '3', '3', '-1', '1', 0),
    (2, 'Coruscating yellow flames', 'Assault', '18"', '4', '2', '-1', '1', 0),
    (1, 'Icarus array', 'Heavy', '48"', '6', '8', '-1', '2', 15),
    (2, 'Phosphex bombs', 'Assault', '6"', '1', '8', '-4', 'D3', 0),
    (2, 'Blight grenades', 'Assault', '8"', '1', '4', '0', '1', 5),
    (2, 'Blight launcher', 'Assault', '24"', '2', '6', '-1', '2', 10),
    (2, 'Blightreaper cannon', 'Heavy', '36"', '4', '7', '-2', '1', 25),
    (1, 'Missile launcher (frag)', 'Heavy', '48"', '1', '4', '0', '1', 10),
    (1, 'Missile launcher (krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (2, 'Missile launcher (frag)', 'Heavy', '48"', '1', '4', '0', '1', 10),
    (2, 'Missile launcher (krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (1, 'Typhoon missile launcher (frag)', 'Heavy', '48"', '2', '4', '0', '1', 10),
    (1, 'Typhoon missile launcher (krak)', 'Heavy', '48"', '2', '9', '-2', 'D6', 10),
    (1, 'Stormstrike missile launcher', 'Heavy', '48"', '1', '8', '-4', 'D6', 20),
    (2, 'Stormstrike missile launcher', 'Heavy', '48"', '1', '8', '-4', 'D6', 20),
    (1, 'Skyhammer missile launcher', 'Heavy', '60"', '3', '7', '-1', 'D3', 20),
    (2, 'Skyhammer missile launcher', 'Heavy', '60"', '3', '7', '-1', 'D3', 20),
    (1, 'Deathwind launcher', 'Heavy', '12"', '1', '12', '0', 'D6+1', 5),
    (1, 'Fragstorm grenade launcher', 'Heavy', '18"', 'D3', '4', '0', '1', 5),
    (1, 'Ironstorm missile pod', 'Heavy', '48"', '1', '5', '0', 'D3', 20),
    (1, 'Hellfyre missile rack', 'Heavy', '36"', '2', '10', '-2', '3', 25),
    (1, 'Daedalus missile launcher', 'Heavy', '48"', '1', '10', '-2', 'D6+1', 20),
    (1, 'Blackstar rocket launcher (Corvid warhead)', 'Heavy', '30"', 'D6', '6', '-2', 'D6', 10),
    (1, 'Blackstar rocket launcher (Dracos warhead)', 'Heavy', '30"', '1', '4', '-1', 'D3', 10),
    (1, 'Blackstar cluster launcher (Frag cluster)', 'Bomb', '-', '1', '4', '0', 'D3+1', 10),
    (1, 'Blackstar cluster launcher (Infernus cluster)', 'Bomb', '-', '1', '5', '-2', 'D3', 10),
    (1, 'Bellicatus missile array (frag)', 'Heavy', '48"', '1', '4', '0', '1', 5),
    (1, 'Bellicatus missile array (icarus)', 'Heavy', '48"', '1', '8', '-1', '2', 10),
    (1, 'Bellicatus missile array (krak)', 'Heavy', '48"', '1', '9', '-2', 'D6', 10),
    (1, 'Repulsor defensive array', 'Assault', '18"', '4', '5', '-1', '1', 20),
    (1, 'Icarus rocket pod', 'Heavy', '24"', '1', '8', '-1', '2', 10),
    (1, 'Exitus pistol', 'Pistol', '12"', '3', '5', '-2', '3', 10),
    (1, 'Exitus rifle', 'Heavy', '48"', '1', '7', '-3', 'D3+3', 20),
    (1, 'Animus speculum', 'Assault', '24"', 'Absorbed warp charge', '5', '-2', 'D3', 20),
    (1, 'Executioner (Needle pistol)', 'Pistol', '12"', '4', '2', '0', '1', 10),
    (1, 'Executioner (Bolt pistol)', 'Pistol', '12"', '4', '4', '0', '1', 5),
    (1, 'Neural shredder', 'Pistol', 'Template', '1', '1', '-4', 'D3', 15),
    (1, 'Infernus', 'Assault', '18"', '2', '8', '-5', 'D6', 0),
    (1, 'The Spear of Telesto', 'Assault', '12"', '1', '7', '-5', 'D3+3', 0),
    (1, 'The Furnaces Heart', 'Assault', '18"', '1', '6', '-4', 'D6', 0),
    (1, 'The Ardent Blade', 'Assault', 'Template', '1', '6', '-2', '1', 0),
    (2, 'The Widowmakers', 'Assault', '12"', '3', '4', '-1', '2', 0),
    (2, 'The Lantern', 'Assault, Pistol', '18"', '1', '9', '-4', '.3', 0),

    (1, 'Castigation', 'Psychic', '18"', '1', '8', '-2', '3', 0),
    (1, 'Cleanse (Witchfire)', 'Psychic', '24"', 'D6', '5', '-1', 'D3', 0),
    (1, 'Cleanse (Focused Witchfire)', 'Psychic', '24"', 'D6', '6', '-2', 'D3', 0),
    (1, 'Smite (Witchfire)', 'Psychic', 'Melee', '+1', '+1', '-2', '2', 0),
    (1, 'Smite (Focused Witchfire)', 'Psychic', 'User', '+1', '+1', '-2', '2', 0),
    (2, 'Infernal Gaze (Witchfire)', 'Psychic', '24"', 'D6', '5', '-1', 'D3', 0),
    (2, 'Infernal Gaze (Focused Witchfire)', 'Psychic', '24"', 'D6', '6', '-2', 'D3', 0),
    (2, 'Rotwind', 'Psychic', '18"', '1', '7', '-2', 'D6+3', 0),
    (2, 'Plague Wind (Witchfire)', 'Psychic', 'Template', '2', '4', '-1', 'D6', 0),
    (2, 'Plague Wind (Focused Witchfire)', 'Psychic', 'Template', '2', '6', '-2', 'D6+3', 0),
    (2, 'Psyfire serpenta', 'Psychic', '15"', 'D3', '8', '-4', '1', 0),
    (2, 'Gaze of Magnus', 'Psychic', '24"', '3D3', '9', '-2', '3', 0),
    (2, 'Tzeentch’s Firestorm', 'Psychic', '24"', '2', '5', '-1', 'D6+3', 0),
    (2, 'Psychic Stalk', 'Psychic', '18"', '1', '6', '-1', 'D6', 0),
    (2, 'Arcane Fire', 'Psychic', 'Template', '1', '6', '-2', '1', 0),
    (2, 'Astral Blast', 'Psychic', '18"', 'D3', '6', '-2', '1', 0),
    (2, 'Warpsmite', 'Psychic', '18"', '1', '4', '-1', '1', 0),
    (2, 'Mutating Orbs', 'Psychic', '18"', '1', '9', '0', 'D3+1', 0),
    (2, 'Infernal Gateway (Witchfire)', 'Psychic', '24"', 'D6+3', '9', '-2', 'D3', 0),
    (2, 'Infernal Gateway (Focused Witchfire)', 'Psychic', '24"', 'D3+1', '9', '-3', 'D3', 0),
    (2, 'Infernal Flames (Witchfire)', 'Psychic', 'Template', '1', '6', '-1', '1', 0),
    (2, 'Infernal Flames (Focused Witchfire)', 'Psychic', 'Template', 'D3', '6', '-1', 'D3+1', 0),
    (2, 'Infernal cannon', 'Psychic', '24"', '6', '5', '-1', '2', 0),
    (2, 'Arcane Fireball (Witchfire)', 'Psychic', '18"', '3', '5', '-1', 'D3', 0),
    (2, 'Arcane Fireball (Focused Witchfire)', 'Psychic', '18"', '3', '6', '-2', 'D3', 0),
    (2, 'Warp Gaze', 'Psychic', '48"', '1', '12', '-2', '3', 0),
    (2, 'Hellfire Breath', 'Psychic', 'Template', '1', '5', '-1', '1', 0),
    (2, 'Torrent of burning blood', 'Psychic', 'Template', '1', '5', '-1', '2', 0),

    (1, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Close combat weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Vehicles close combat', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (1, 'Combat knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Combat knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Improvised weapon', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Chakhal flails', 'Melee', 'Melee', 'User', '+1', '0', '1', 0),
    (2, 'Chakhal mauler', 'Melee', 'Melee', 'User', '+2', '-1', '2', 0),
    (2, 'Dishonoured chainblades', 'Melee', 'Melee', '+1', '+1', '0', '1', 0),
    (2, 'Skullsmasher', 'Melee', 'Melee', '+2', '+1', '-1', '2', 0),
    (2, 'Pink claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Blue claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Yellow claws', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Plague knife', 'Melee', 'Melee', 'User', 'User', '0', '1', 5),
    (1, 'Combat blade', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (1, 'Paired combat blade', 'Melee', 'Melee', 'User', 'User', '-1', '1', 10),
    (1, 'Astartes chainsword', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (2, 'Astartes chainsword', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (2, 'Berzerker chainsword', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (2, 'Berzerker chainaxe', 'Melee', 'Melee', 'User', 'User', '-2', '2', 10),
    (2, 'Nostraman chainglaive', 'Melee', 'Melee', 'User', '+1', '0', '2', 0),
    (2, 'Hideous Mutation', 'Melee', 'Melee', 'User', 'User', '-1', '2', 5),
    (1, 'Force axe', 'Melee', 'Melee', 'User', '+2', '-2', 'D3', 15),
    (2, 'Force axe', 'Melee', 'Melee', 'User', '+2', '-2', 'D3', 15),
    (1, 'Force maul', 'Melee', 'Melee', 'User', '+3', '-1', 'D3', 15),
    (2, 'Force maul', 'Melee', 'Melee', 'User', '+3', '-1', 'D3', 15),
    (1, 'Force sword', 'Melee', 'Melee', 'User', '+1', '-3', 'D3', 15),
    (2, 'Force sword', 'Melee', 'Melee', 'User', '+1', '-3', 'D3', 15),
    (2, 'Prosperine khopesh', 'Melee', 'Melee', 'User', '+1', '-3', '1', 15),
    (2, 'Force stave', 'Melee', 'Melee', 'User', '+3', '-1', '3', 15),
    (2, 'Shaman stave', 'Melee', 'Melee', 'User', '+2', '-1', 'D3', 10),
    (2, 'Corrupted staff', 'Melee', 'Melee', 'User', '+2', '-1', 'D3', 15),
    (1, 'Power axe', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (2, 'Power axe', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (2, 'Axe of dismemberment', 'Melee', 'Melee', 'User', '+3', '-2', '2', 15),
    (1, 'Power maul', 'Melee', 'Melee', 'User', '+3', '-1', '1', 10),
    (2, 'Power maul', 'Melee', 'Melee', 'User', '+3', '-1', '1', 10),
    (1, 'Power sword', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (2, 'Power sword', 'Melee', 'Melee', 'User', '+1', '-3', '1', 10),
    (2, 'Balesword', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Blade of blood', 'Melee', 'Melee', 'User', '+1', '-2', '3', 10),
    (2, 'Attendant hellblades', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Hellbalde', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Divining spear', 'Melee', 'Melee', 'User', '+2', '-2', '1', 10),
    (1, 'Crozius Arcanum', 'Melee', 'Melee', 'User', '+2', '-1', '2', 10),
    (1, 'Relic blade', 'Melee','Melee', '+1', '+1', '-2', '2', 10),
    (2, 'Exalted weapon', 'Melee', 'Melee', '+2', '+1', '-2', '2', 20),
    (2, 'Daemon blade', 'Melee', 'Melee', '+1', '+3', '-3', 'D3', 25),
    (1, 'Executioner relic blade', 'Melee','Melee', '+1', '+3', '-2', '2', 15),
    (1, 'Xenophase blade', 'Melee','Melee', '+1', '+1', '-3', '3', 20),
    (1, 'Life-draining touch', 'Melee', 'Melee', 'User', 'User', '-2', '2', 10),
    (1, 'Neuro gauntlet', 'Melee', 'Melee', '-1', '+1', '0', '2', 10),
    (1, 'Phase sword', 'Melee','Melee', 'User', '+1', '-4', '1', 15),
    (1, 'Poison Blades', 'Melee','Melee', 'User', '+1', '0', '2', 10),
    (2, 'Bubotic weapon', 'Melee', 'Melee', 'User', '+1', '-2', '1', 15),
    (2, 'Bubotic axe & Mace of Contagion', 'Melee', 'Melee', '+1', '+1', '-2', '2', 20),
    (2, 'Heavy plague weapon', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 25),
    (2, 'Cursed plague bell', 'Melee', 'Melee', '+1', 'User', '0', '2', 5),
    (1, 'Arc scourge', 'Melee','Melee', 'User', '+1', '-1', '1', 5),
    (1, 'Arc maul', 'Melee','Melee', 'User', '+3', '-2', '2', 15),
    (1, 'Taser goad', 'Melee','Melee', 'User', '+3', '0', '2', 10),
    (1, 'Mechadendrite hive', 'Melee','Melee', '2D6', 'User', '0', '1', 5),
    (1, 'Servo-arm', 'Melee', 'Melee', '1', 'x2', '-2', '3', 15),
    (1, 'Omnissian power axe', 'Melee', 'Melee', 'User', '+2', '-2', '2', 15),
    (1, 'Crawls omnissian axe', 'Melee', 'Melee', 'User', '+4', '-2', '2', 20),
    (1, 'Vigil Spear (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', 'D3', 10),
    (1, 'Vigil Spear (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (2, 'Manreaper (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 10),
    (2, 'Manreaper (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 10),
    (2, 'Plagueblade (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 10),
    (2, 'Plagueblade (Sweep)', 'Melee', 'Melee', 'x2', 'User', '0', '1', 10),
    (2, 'Plague probe', 'Melee', 'Melee', 'User', 'User', '-1', '1', 5),
    (2, 'Greater plague probe', 'Melee', 'Melee', 'User', 'User', '-2', '1', 5),
    (2, 'Bile maw', 'Melee', 'Melee', 'User', '+2', '-1', '1', 5),
    (2, 'Great axe of Khorne (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', 'D6+2', 30),
    (2, 'Great axe of Khorne (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '2', 25),
    (2, 'Tzaangor blades', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Tzaangor heavy blades', 'Melee', 'Melee', '-1', '+2', '-1', '1', 5),
    (2, 'Flamer mouths', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'Lamprey bites', 'Melee', 'Melee', 'User', 'User', '-2', '2', 5),
    (2, 'Juggernaut bladed horn', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Soul-rending fangs', 'Melee', 'Melee', 'User', 'User', '-1', '2', 5),
    (2, 'Gore-denched fangs', 'Melee', 'Melee', 'User', 'User', '-1', '1', 0),
    (2, 'Biting maw', 'Melee', 'Melee', 'User', 'User', '0', '2', 0),
    (1, 'Power fist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 15),
    (2, 'Power fist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 15),
    (2, 'Bubotic power fist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (2, 'Lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 10),
    (1, 'Twin lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 15),
    (2, 'Twin lightning claw', 'Melee', 'Melee', 'User', '+1', '-2', '2', 15),
    (2, 'Warp claws', 'Melee', 'Melee', '+1', '+1', '-2', '1', 10),
    (2, 'Warpclaw', 'Melee', 'Melee', '+1', 'User', '-1', '2', 0),
    (2, 'Warpsword', 'Melee', 'Melee', 'User', 'User', '-2', 'D6', 5),
    (2, 'Daemons claw', 'Melee', 'Melee', 'User', 'user', '0', '1', 0),
    (2, 'Mutating warpblade (Strike)', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 25),
    (2, 'Mutating warpblade (Sweep)', 'Melee', 'Melee', 'x2', 'User', '0', '1', 25),
    (1, 'Chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (2, 'Thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-2', '2', 20),
    (1, 'Heavy thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-4', '3', 25),
    (2, 'Heavy thunder hammer', 'Melee', 'Melee', '-1', 'x2', '-4', '3', 25),
    (1, 'Boltstorm', 'Melee', 'Melee', '-2', 'x2', '-2', '3', 20),
    (1, 'Kastelan fist', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (1, 'Invictor fist', 'Melee', 'Melee', '+1', 'x2', '-2', '3', 20),
    (1, 'Dreadnought combat weapon', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (2, 'Dreadnought combat weapon', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (1, 'Dreadnought lightning claw', 'Melee', 'Melee', '+1', '+1', '-2', '3', 15),
    (2, 'Dreadnought lightning claw', 'Melee', 'Melee', '+1', '+1', '-2', '3', 15),
    (1, 'Dreadnought chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '3', 25),
    (2, 'Dreadnought chainfist', 'Melee', 'Melee', '-1', 'x2', '-2', '3', 25),
    (2, 'Helbrute fist', 'Melee', 'Melee', 'User', 'x2', '-2', '3', 20),
    (2, 'Defiler claw', 'Melee', 'Melee', 'User', 'x2', '-2', 'D3+3', 25),
    (2, 'Defiler scourge', 'Melee', 'Melee', '+2', '+4', '-1', '2', 20),
    (2, 'Bubotic defiler scourge', 'Melee', 'Melee', '+2', '+4', '-1', '2', 25),
    (1, 'Thuderstrike gauntlet (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '8', 25),
    (1, 'Thuderstrike gauntlet (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '3', 25),
    (1, 'Reaper chaincleaver (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 15),
    (1, 'Reaper chaincleaver (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '1', 15),
    (1, 'Reaper chainsword (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', '6', 20),
    (1, 'Reaper chainsword (Sweep)', 'Melee', 'Melee', 'x3', 'User', '-3', '2', 25),
    (1, 'Black Sword (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 0),
    (1, 'Black Sword (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-2', '1', 0),
    (1, 'The Spear of Telesto (Strike)', 'Melee', 'Melee', 'User', 'x2', '-4', 'D3+1', 0),
    (1, 'The Spear of Telesto (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-3', 'D3', 0),
    (1, 'Moonsilver', 'Melee', 'Melee', 'User', 'User', '-3', '2', 0),
    (1, 'Dawnbringer', 'Melee', 'Melee', 'User', '+3', '-5', 'D3+3', 0),
    (1, 'The Ardent Blade', 'Melee', 'Melee', '+1', '+1', '-3', '1', 0),
    (2, 'Mercy & Forgiveness', 'Melee', 'Melee', 'User', '+1', '-4', 'D6', 0),
    (2, 'Claws of the Black Hunt', 'Melee', 'Melee', '+3', '+2', '-3', 'D3+2', 35),
    (2, 'Silence (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '4', 0),
    (2, 'Silence (Sweep)', 'Melee', 'Melee', 'x3', 'User', '-1', '1', 0),
    (2, 'The Blade of Ahn-Nunurta (Strike)', 'Melee', 'Melee', 'User', 'x2', '-3', '3', 0),
    (2, 'The Blade of Ahn-Nunurta (Sweep)', 'Melee', 'Melee', 'x2', 'User', '-1', '1', 0),
    (2, 'Black Staff of Ahriman', 'Melee', 'Melee', '+1', '+3', '-1', '3', 0),
    (2, 'Seer’s Bane', 'Melee', 'Melee', 'User', '+1', '-3', 'D3', 0),
    (2, 'Gorechild', 'Melee', 'Melee', 'User', '+2', '-2', '3', 0),
    (2, 'Staff of Tommorrow', 'Melee', 'Melee', 'User', '+2', '-2', '2D3', 0),
    (2, 'The Trickster Staff', 'Melee', 'Melee', 'User', '+1', '-1', 'D3', 0),
    (2, 'Sharp quills', 'Melee', 'Melee', 'User', 'User', '0', '1', 0),
    (2, 'The Slayer Sword', 'Melee', 'Melee', 'User', '+2', '-2', '3', 0)
;


-- Weapon Rules tables
INSERT INTO weapons_rules (weapon_id, rule_id)
VALUES
    (1, 1),
    (1, 2)
;